// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: identity.proto

package sawtooth.identity.protobuf;

public interface PolicyListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PolicyList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Policy policies = 1;</code>
   */
  java.util.List<sawtooth.identity.protobuf.Policy> 
      getPoliciesList();
  /**
   * <code>repeated .Policy policies = 1;</code>
   */
  sawtooth.identity.protobuf.Policy getPolicies(int index);
  /**
   * <code>repeated .Policy policies = 1;</code>
   */
  int getPoliciesCount();
  /**
   * <code>repeated .Policy policies = 1;</code>
   */
  java.util.List<? extends sawtooth.identity.protobuf.PolicyOrBuilder> 
      getPoliciesOrBuilderList();
  /**
   * <code>repeated .Policy policies = 1;</code>
   */
  sawtooth.identity.protobuf.PolicyOrBuilder getPoliciesOrBuilder(
      int index);
}
