// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: authorization.proto

package sawtooth.sdk.protobuf;

public interface AuthorizationChallengeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AuthorizationChallengeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Random payload that the connecting node must sign
   * </pre>
   *
   * <code>bytes payload = 1;</code>
   */
  com.google.protobuf.ByteString getPayload();
}
