// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: authorization.proto

package sawtooth.sdk.protobuf;

public interface AuthorizationTrustResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AuthorizationTrustResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The actual set the requester has access to
   * </pre>
   *
   * <code>repeated .RoleType roles = 1;</code>
   */
  java.util.List<sawtooth.sdk.protobuf.RoleType> getRolesList();
  /**
   * <pre>
   * The actual set the requester has access to
   * </pre>
   *
   * <code>repeated .RoleType roles = 1;</code>
   */
  int getRolesCount();
  /**
   * <pre>
   * The actual set the requester has access to
   * </pre>
   *
   * <code>repeated .RoleType roles = 1;</code>
   */
  sawtooth.sdk.protobuf.RoleType getRoles(int index);
  /**
   * <pre>
   * The actual set the requester has access to
   * </pre>
   *
   * <code>repeated .RoleType roles = 1;</code>
   */
  java.util.List<java.lang.Integer>
  getRolesValueList();
  /**
   * <pre>
   * The actual set the requester has access to
   * </pre>
   *
   * <code>repeated .RoleType roles = 1;</code>
   */
  int getRolesValue(int index);
}
