// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: authorization.proto

package sawtooth.sdk.protobuf;

public final class Authorization {
  private Authorization() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConnectionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConnectionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConnectionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConnectionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConnectionResponse_RoleEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConnectionResponse_RoleEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AuthorizationTrustRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AuthorizationTrustRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AuthorizationTrustResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AuthorizationTrustResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AuthorizationViolation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AuthorizationViolation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AuthorizationChallengeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AuthorizationChallengeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AuthorizationChallengeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AuthorizationChallengeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AuthorizationChallengeSubmit_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AuthorizationChallengeSubmit_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AuthorizationChallengeResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AuthorizationChallengeResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023authorization.proto\"%\n\021ConnectionReque" +
      "st\022\020\n\010endpoint\030\001 \001(\t\"\312\002\n\022ConnectionRespo" +
      "nse\022,\n\005roles\030\001 \003(\0132\035.ConnectionResponse." +
      "RoleEntry\022*\n\006status\030\002 \001(\0162\032.ConnectionRe" +
      "sponse.Status\032^\n\tRoleEntry\022\027\n\004role\030\001 \001(\016" +
      "2\t.RoleType\0228\n\tauth_type\030\002 \001(\0162%.Connect" +
      "ionResponse.AuthorizationType\"-\n\006Status\022" +
      "\020\n\014STATUS_UNSET\020\000\022\006\n\002OK\020\001\022\t\n\005ERROR\020\002\"K\n\021" +
      "AuthorizationType\022\034\n\030AUTHORIZATION_TYPE_" +
      "UNSET\020\000\022\t\n\005TRUST\020\001\022\r\n\tCHALLENGE\020\002\"I\n\031Aut" +
      "horizationTrustRequest\022\030\n\005roles\030\001 \003(\0162\t." +
      "RoleType\022\022\n\npublic_key\030\002 \001(\t\"6\n\032Authoriz" +
      "ationTrustResponse\022\030\n\005roles\030\001 \003(\0162\t.Role" +
      "Type\"6\n\026AuthorizationViolation\022\034\n\tviolat" +
      "ion\030\001 \001(\0162\t.RoleType\"\037\n\035AuthorizationCha" +
      "llengeRequest\"1\n\036AuthorizationChallengeR" +
      "esponse\022\017\n\007payload\030\001 \001(\014\"_\n\034Authorizatio" +
      "nChallengeSubmit\022\022\n\npublic_key\030\001 \001(\t\022\021\n\t" +
      "signature\030\003 \001(\t\022\030\n\005roles\030\004 \003(\0162\t.RoleTyp" +
      "e\"8\n\034AuthorizationChallengeResult\022\030\n\005rol" +
      "es\030\001 \003(\0162\t.RoleType*5\n\010RoleType\022\023\n\017ROLE_" +
      "TYPE_UNSET\020\000\022\007\n\003ALL\020\001\022\013\n\007NETWORK\020\002B,\n\025sa" +
      "wtooth.sdk.protobufP\001Z\021authorization_pb2" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ConnectionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ConnectionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConnectionRequest_descriptor,
        new java.lang.String[] { "Endpoint", });
    internal_static_ConnectionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ConnectionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConnectionResponse_descriptor,
        new java.lang.String[] { "Roles", "Status", });
    internal_static_ConnectionResponse_RoleEntry_descriptor =
      internal_static_ConnectionResponse_descriptor.getNestedTypes().get(0);
    internal_static_ConnectionResponse_RoleEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConnectionResponse_RoleEntry_descriptor,
        new java.lang.String[] { "Role", "AuthType", });
    internal_static_AuthorizationTrustRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_AuthorizationTrustRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AuthorizationTrustRequest_descriptor,
        new java.lang.String[] { "Roles", "PublicKey", });
    internal_static_AuthorizationTrustResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_AuthorizationTrustResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AuthorizationTrustResponse_descriptor,
        new java.lang.String[] { "Roles", });
    internal_static_AuthorizationViolation_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_AuthorizationViolation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AuthorizationViolation_descriptor,
        new java.lang.String[] { "Violation", });
    internal_static_AuthorizationChallengeRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_AuthorizationChallengeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AuthorizationChallengeRequest_descriptor,
        new java.lang.String[] { });
    internal_static_AuthorizationChallengeResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_AuthorizationChallengeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AuthorizationChallengeResponse_descriptor,
        new java.lang.String[] { "Payload", });
    internal_static_AuthorizationChallengeSubmit_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_AuthorizationChallengeSubmit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AuthorizationChallengeSubmit_descriptor,
        new java.lang.String[] { "PublicKey", "Signature", "Roles", });
    internal_static_AuthorizationChallengeResult_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_AuthorizationChallengeResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AuthorizationChallengeResult_descriptor,
        new java.lang.String[] { "Roles", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
