// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: merkle.proto

package sawtooth.sdk.protobuf;

/**
 * <pre>
 * An Entry in the change log for a given state root.
 * </pre>
 *
 * Protobuf type {@code ChangeLogEntry}
 */
public  final class ChangeLogEntry extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ChangeLogEntry)
    ChangeLogEntryOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ChangeLogEntry.newBuilder() to construct.
  private ChangeLogEntry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ChangeLogEntry() {
    parent_ = com.google.protobuf.ByteString.EMPTY;
    additions_ = java.util.Collections.emptyList();
    successors_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ChangeLogEntry(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {

            parent_ = input.readBytes();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              additions_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
              mutable_bitField0_ |= 0x00000002;
            }
            additions_.add(input.readBytes());
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              successors_ = new java.util.ArrayList<sawtooth.sdk.protobuf.ChangeLogEntry.Successor>();
              mutable_bitField0_ |= 0x00000004;
            }
            successors_.add(
                input.readMessage(sawtooth.sdk.protobuf.ChangeLogEntry.Successor.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        additions_ = java.util.Collections.unmodifiableList(additions_);
      }
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        successors_ = java.util.Collections.unmodifiableList(successors_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return sawtooth.sdk.protobuf.Merkle.internal_static_ChangeLogEntry_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return sawtooth.sdk.protobuf.Merkle.internal_static_ChangeLogEntry_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            sawtooth.sdk.protobuf.ChangeLogEntry.class, sawtooth.sdk.protobuf.ChangeLogEntry.Builder.class);
  }

  public interface SuccessorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ChangeLogEntry.Successor)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * A root hash of a merkle trie based of off this root.
     * </pre>
     *
     * <code>bytes successor = 1;</code>
     */
    com.google.protobuf.ByteString getSuccessor();

    /**
     * <pre>
     * The keys (i.e. hashes) that were replaced (i.e. deleted) by this
     * successor.  These may be deleted during pruning.
     * </pre>
     *
     * <code>repeated bytes deletions = 2;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getDeletionsList();
    /**
     * <pre>
     * The keys (i.e. hashes) that were replaced (i.e. deleted) by this
     * successor.  These may be deleted during pruning.
     * </pre>
     *
     * <code>repeated bytes deletions = 2;</code>
     */
    int getDeletionsCount();
    /**
     * <pre>
     * The keys (i.e. hashes) that were replaced (i.e. deleted) by this
     * successor.  These may be deleted during pruning.
     * </pre>
     *
     * <code>repeated bytes deletions = 2;</code>
     */
    com.google.protobuf.ByteString getDeletions(int index);
  }
  /**
   * <pre>
   * A state root that succeed this root.
   * </pre>
   *
   * Protobuf type {@code ChangeLogEntry.Successor}
   */
  public  static final class Successor extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ChangeLogEntry.Successor)
      SuccessorOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Successor.newBuilder() to construct.
    private Successor(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Successor() {
      successor_ = com.google.protobuf.ByteString.EMPTY;
      deletions_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Successor(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              successor_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                deletions_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000002;
              }
              deletions_.add(input.readBytes());
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          deletions_ = java.util.Collections.unmodifiableList(deletions_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sawtooth.sdk.protobuf.Merkle.internal_static_ChangeLogEntry_Successor_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sawtooth.sdk.protobuf.Merkle.internal_static_ChangeLogEntry_Successor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sawtooth.sdk.protobuf.ChangeLogEntry.Successor.class, sawtooth.sdk.protobuf.ChangeLogEntry.Successor.Builder.class);
    }

    private int bitField0_;
    public static final int SUCCESSOR_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString successor_;
    /**
     * <pre>
     * A root hash of a merkle trie based of off this root.
     * </pre>
     *
     * <code>bytes successor = 1;</code>
     */
    public com.google.protobuf.ByteString getSuccessor() {
      return successor_;
    }

    public static final int DELETIONS_FIELD_NUMBER = 2;
    private java.util.List<com.google.protobuf.ByteString> deletions_;
    /**
     * <pre>
     * The keys (i.e. hashes) that were replaced (i.e. deleted) by this
     * successor.  These may be deleted during pruning.
     * </pre>
     *
     * <code>repeated bytes deletions = 2;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getDeletionsList() {
      return deletions_;
    }
    /**
     * <pre>
     * The keys (i.e. hashes) that were replaced (i.e. deleted) by this
     * successor.  These may be deleted during pruning.
     * </pre>
     *
     * <code>repeated bytes deletions = 2;</code>
     */
    public int getDeletionsCount() {
      return deletions_.size();
    }
    /**
     * <pre>
     * The keys (i.e. hashes) that were replaced (i.e. deleted) by this
     * successor.  These may be deleted during pruning.
     * </pre>
     *
     * <code>repeated bytes deletions = 2;</code>
     */
    public com.google.protobuf.ByteString getDeletions(int index) {
      return deletions_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!successor_.isEmpty()) {
        output.writeBytes(1, successor_);
      }
      for (int i = 0; i < deletions_.size(); i++) {
        output.writeBytes(2, deletions_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!successor_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, successor_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < deletions_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(deletions_.get(i));
        }
        size += dataSize;
        size += 1 * getDeletionsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sawtooth.sdk.protobuf.ChangeLogEntry.Successor)) {
        return super.equals(obj);
      }
      sawtooth.sdk.protobuf.ChangeLogEntry.Successor other = (sawtooth.sdk.protobuf.ChangeLogEntry.Successor) obj;

      boolean result = true;
      result = result && getSuccessor()
          .equals(other.getSuccessor());
      result = result && getDeletionsList()
          .equals(other.getDeletionsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUCCESSOR_FIELD_NUMBER;
      hash = (53 * hash) + getSuccessor().hashCode();
      if (getDeletionsCount() > 0) {
        hash = (37 * hash) + DELETIONS_FIELD_NUMBER;
        hash = (53 * hash) + getDeletionsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sawtooth.sdk.protobuf.ChangeLogEntry.Successor parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sawtooth.sdk.protobuf.ChangeLogEntry.Successor parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sawtooth.sdk.protobuf.ChangeLogEntry.Successor parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sawtooth.sdk.protobuf.ChangeLogEntry.Successor parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sawtooth.sdk.protobuf.ChangeLogEntry.Successor parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sawtooth.sdk.protobuf.ChangeLogEntry.Successor parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sawtooth.sdk.protobuf.ChangeLogEntry.Successor parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sawtooth.sdk.protobuf.ChangeLogEntry.Successor parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static sawtooth.sdk.protobuf.ChangeLogEntry.Successor parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static sawtooth.sdk.protobuf.ChangeLogEntry.Successor parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sawtooth.sdk.protobuf.ChangeLogEntry.Successor parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sawtooth.sdk.protobuf.ChangeLogEntry.Successor parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sawtooth.sdk.protobuf.ChangeLogEntry.Successor prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * A state root that succeed this root.
     * </pre>
     *
     * Protobuf type {@code ChangeLogEntry.Successor}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ChangeLogEntry.Successor)
        sawtooth.sdk.protobuf.ChangeLogEntry.SuccessorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sawtooth.sdk.protobuf.Merkle.internal_static_ChangeLogEntry_Successor_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sawtooth.sdk.protobuf.Merkle.internal_static_ChangeLogEntry_Successor_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sawtooth.sdk.protobuf.ChangeLogEntry.Successor.class, sawtooth.sdk.protobuf.ChangeLogEntry.Successor.Builder.class);
      }

      // Construct using sawtooth.sdk.protobuf.ChangeLogEntry.Successor.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        successor_ = com.google.protobuf.ByteString.EMPTY;

        deletions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sawtooth.sdk.protobuf.Merkle.internal_static_ChangeLogEntry_Successor_descriptor;
      }

      @java.lang.Override
      public sawtooth.sdk.protobuf.ChangeLogEntry.Successor getDefaultInstanceForType() {
        return sawtooth.sdk.protobuf.ChangeLogEntry.Successor.getDefaultInstance();
      }

      @java.lang.Override
      public sawtooth.sdk.protobuf.ChangeLogEntry.Successor build() {
        sawtooth.sdk.protobuf.ChangeLogEntry.Successor result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sawtooth.sdk.protobuf.ChangeLogEntry.Successor buildPartial() {
        sawtooth.sdk.protobuf.ChangeLogEntry.Successor result = new sawtooth.sdk.protobuf.ChangeLogEntry.Successor(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.successor_ = successor_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          deletions_ = java.util.Collections.unmodifiableList(deletions_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.deletions_ = deletions_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sawtooth.sdk.protobuf.ChangeLogEntry.Successor) {
          return mergeFrom((sawtooth.sdk.protobuf.ChangeLogEntry.Successor)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sawtooth.sdk.protobuf.ChangeLogEntry.Successor other) {
        if (other == sawtooth.sdk.protobuf.ChangeLogEntry.Successor.getDefaultInstance()) return this;
        if (other.getSuccessor() != com.google.protobuf.ByteString.EMPTY) {
          setSuccessor(other.getSuccessor());
        }
        if (!other.deletions_.isEmpty()) {
          if (deletions_.isEmpty()) {
            deletions_ = other.deletions_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureDeletionsIsMutable();
            deletions_.addAll(other.deletions_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sawtooth.sdk.protobuf.ChangeLogEntry.Successor parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sawtooth.sdk.protobuf.ChangeLogEntry.Successor) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString successor_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * A root hash of a merkle trie based of off this root.
       * </pre>
       *
       * <code>bytes successor = 1;</code>
       */
      public com.google.protobuf.ByteString getSuccessor() {
        return successor_;
      }
      /**
       * <pre>
       * A root hash of a merkle trie based of off this root.
       * </pre>
       *
       * <code>bytes successor = 1;</code>
       */
      public Builder setSuccessor(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        successor_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * A root hash of a merkle trie based of off this root.
       * </pre>
       *
       * <code>bytes successor = 1;</code>
       */
      public Builder clearSuccessor() {
        
        successor_ = getDefaultInstance().getSuccessor();
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> deletions_ = java.util.Collections.emptyList();
      private void ensureDeletionsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          deletions_ = new java.util.ArrayList<com.google.protobuf.ByteString>(deletions_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <pre>
       * The keys (i.e. hashes) that were replaced (i.e. deleted) by this
       * successor.  These may be deleted during pruning.
       * </pre>
       *
       * <code>repeated bytes deletions = 2;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getDeletionsList() {
        return java.util.Collections.unmodifiableList(deletions_);
      }
      /**
       * <pre>
       * The keys (i.e. hashes) that were replaced (i.e. deleted) by this
       * successor.  These may be deleted during pruning.
       * </pre>
       *
       * <code>repeated bytes deletions = 2;</code>
       */
      public int getDeletionsCount() {
        return deletions_.size();
      }
      /**
       * <pre>
       * The keys (i.e. hashes) that were replaced (i.e. deleted) by this
       * successor.  These may be deleted during pruning.
       * </pre>
       *
       * <code>repeated bytes deletions = 2;</code>
       */
      public com.google.protobuf.ByteString getDeletions(int index) {
        return deletions_.get(index);
      }
      /**
       * <pre>
       * The keys (i.e. hashes) that were replaced (i.e. deleted) by this
       * successor.  These may be deleted during pruning.
       * </pre>
       *
       * <code>repeated bytes deletions = 2;</code>
       */
      public Builder setDeletions(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDeletionsIsMutable();
        deletions_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The keys (i.e. hashes) that were replaced (i.e. deleted) by this
       * successor.  These may be deleted during pruning.
       * </pre>
       *
       * <code>repeated bytes deletions = 2;</code>
       */
      public Builder addDeletions(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDeletionsIsMutable();
        deletions_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The keys (i.e. hashes) that were replaced (i.e. deleted) by this
       * successor.  These may be deleted during pruning.
       * </pre>
       *
       * <code>repeated bytes deletions = 2;</code>
       */
      public Builder addAllDeletions(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureDeletionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, deletions_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The keys (i.e. hashes) that were replaced (i.e. deleted) by this
       * successor.  These may be deleted during pruning.
       * </pre>
       *
       * <code>repeated bytes deletions = 2;</code>
       */
      public Builder clearDeletions() {
        deletions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ChangeLogEntry.Successor)
    }

    // @@protoc_insertion_point(class_scope:ChangeLogEntry.Successor)
    private static final sawtooth.sdk.protobuf.ChangeLogEntry.Successor DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sawtooth.sdk.protobuf.ChangeLogEntry.Successor();
    }

    public static sawtooth.sdk.protobuf.ChangeLogEntry.Successor getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Successor>
        PARSER = new com.google.protobuf.AbstractParser<Successor>() {
      @java.lang.Override
      public Successor parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Successor(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Successor> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Successor> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sawtooth.sdk.protobuf.ChangeLogEntry.Successor getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int PARENT_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString parent_;
  /**
   * <pre>
   * A root hash of a merkle trie this tree was based off.
   * </pre>
   *
   * <code>bytes parent = 1;</code>
   */
  public com.google.protobuf.ByteString getParent() {
    return parent_;
  }

  public static final int ADDITIONS_FIELD_NUMBER = 2;
  private java.util.List<com.google.protobuf.ByteString> additions_;
  /**
   * <pre>
   * The hashes that were added for this root. These may be deleted during
   * pruning, if this root is being abandoned.
   * </pre>
   *
   * <code>repeated bytes additions = 2;</code>
   */
  public java.util.List<com.google.protobuf.ByteString>
      getAdditionsList() {
    return additions_;
  }
  /**
   * <pre>
   * The hashes that were added for this root. These may be deleted during
   * pruning, if this root is being abandoned.
   * </pre>
   *
   * <code>repeated bytes additions = 2;</code>
   */
  public int getAdditionsCount() {
    return additions_.size();
  }
  /**
   * <pre>
   * The hashes that were added for this root. These may be deleted during
   * pruning, if this root is being abandoned.
   * </pre>
   *
   * <code>repeated bytes additions = 2;</code>
   */
  public com.google.protobuf.ByteString getAdditions(int index) {
    return additions_.get(index);
  }

  public static final int SUCCESSORS_FIELD_NUMBER = 3;
  private java.util.List<sawtooth.sdk.protobuf.ChangeLogEntry.Successor> successors_;
  /**
   * <pre>
   * The list of successors.
   * </pre>
   *
   * <code>repeated .ChangeLogEntry.Successor successors = 3;</code>
   */
  public java.util.List<sawtooth.sdk.protobuf.ChangeLogEntry.Successor> getSuccessorsList() {
    return successors_;
  }
  /**
   * <pre>
   * The list of successors.
   * </pre>
   *
   * <code>repeated .ChangeLogEntry.Successor successors = 3;</code>
   */
  public java.util.List<? extends sawtooth.sdk.protobuf.ChangeLogEntry.SuccessorOrBuilder> 
      getSuccessorsOrBuilderList() {
    return successors_;
  }
  /**
   * <pre>
   * The list of successors.
   * </pre>
   *
   * <code>repeated .ChangeLogEntry.Successor successors = 3;</code>
   */
  public int getSuccessorsCount() {
    return successors_.size();
  }
  /**
   * <pre>
   * The list of successors.
   * </pre>
   *
   * <code>repeated .ChangeLogEntry.Successor successors = 3;</code>
   */
  public sawtooth.sdk.protobuf.ChangeLogEntry.Successor getSuccessors(int index) {
    return successors_.get(index);
  }
  /**
   * <pre>
   * The list of successors.
   * </pre>
   *
   * <code>repeated .ChangeLogEntry.Successor successors = 3;</code>
   */
  public sawtooth.sdk.protobuf.ChangeLogEntry.SuccessorOrBuilder getSuccessorsOrBuilder(
      int index) {
    return successors_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!parent_.isEmpty()) {
      output.writeBytes(1, parent_);
    }
    for (int i = 0; i < additions_.size(); i++) {
      output.writeBytes(2, additions_.get(i));
    }
    for (int i = 0; i < successors_.size(); i++) {
      output.writeMessage(3, successors_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!parent_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, parent_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < additions_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(additions_.get(i));
      }
      size += dataSize;
      size += 1 * getAdditionsList().size();
    }
    for (int i = 0; i < successors_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, successors_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof sawtooth.sdk.protobuf.ChangeLogEntry)) {
      return super.equals(obj);
    }
    sawtooth.sdk.protobuf.ChangeLogEntry other = (sawtooth.sdk.protobuf.ChangeLogEntry) obj;

    boolean result = true;
    result = result && getParent()
        .equals(other.getParent());
    result = result && getAdditionsList()
        .equals(other.getAdditionsList());
    result = result && getSuccessorsList()
        .equals(other.getSuccessorsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PARENT_FIELD_NUMBER;
    hash = (53 * hash) + getParent().hashCode();
    if (getAdditionsCount() > 0) {
      hash = (37 * hash) + ADDITIONS_FIELD_NUMBER;
      hash = (53 * hash) + getAdditionsList().hashCode();
    }
    if (getSuccessorsCount() > 0) {
      hash = (37 * hash) + SUCCESSORS_FIELD_NUMBER;
      hash = (53 * hash) + getSuccessorsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static sawtooth.sdk.protobuf.ChangeLogEntry parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sawtooth.sdk.protobuf.ChangeLogEntry parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sawtooth.sdk.protobuf.ChangeLogEntry parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sawtooth.sdk.protobuf.ChangeLogEntry parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sawtooth.sdk.protobuf.ChangeLogEntry parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sawtooth.sdk.protobuf.ChangeLogEntry parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sawtooth.sdk.protobuf.ChangeLogEntry parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sawtooth.sdk.protobuf.ChangeLogEntry parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static sawtooth.sdk.protobuf.ChangeLogEntry parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static sawtooth.sdk.protobuf.ChangeLogEntry parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static sawtooth.sdk.protobuf.ChangeLogEntry parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sawtooth.sdk.protobuf.ChangeLogEntry parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sawtooth.sdk.protobuf.ChangeLogEntry prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * An Entry in the change log for a given state root.
   * </pre>
   *
   * Protobuf type {@code ChangeLogEntry}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ChangeLogEntry)
      sawtooth.sdk.protobuf.ChangeLogEntryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sawtooth.sdk.protobuf.Merkle.internal_static_ChangeLogEntry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sawtooth.sdk.protobuf.Merkle.internal_static_ChangeLogEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sawtooth.sdk.protobuf.ChangeLogEntry.class, sawtooth.sdk.protobuf.ChangeLogEntry.Builder.class);
    }

    // Construct using sawtooth.sdk.protobuf.ChangeLogEntry.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSuccessorsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      parent_ = com.google.protobuf.ByteString.EMPTY;

      additions_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);
      if (successorsBuilder_ == null) {
        successors_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        successorsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return sawtooth.sdk.protobuf.Merkle.internal_static_ChangeLogEntry_descriptor;
    }

    @java.lang.Override
    public sawtooth.sdk.protobuf.ChangeLogEntry getDefaultInstanceForType() {
      return sawtooth.sdk.protobuf.ChangeLogEntry.getDefaultInstance();
    }

    @java.lang.Override
    public sawtooth.sdk.protobuf.ChangeLogEntry build() {
      sawtooth.sdk.protobuf.ChangeLogEntry result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public sawtooth.sdk.protobuf.ChangeLogEntry buildPartial() {
      sawtooth.sdk.protobuf.ChangeLogEntry result = new sawtooth.sdk.protobuf.ChangeLogEntry(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.parent_ = parent_;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        additions_ = java.util.Collections.unmodifiableList(additions_);
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.additions_ = additions_;
      if (successorsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          successors_ = java.util.Collections.unmodifiableList(successors_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.successors_ = successors_;
      } else {
        result.successors_ = successorsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof sawtooth.sdk.protobuf.ChangeLogEntry) {
        return mergeFrom((sawtooth.sdk.protobuf.ChangeLogEntry)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(sawtooth.sdk.protobuf.ChangeLogEntry other) {
      if (other == sawtooth.sdk.protobuf.ChangeLogEntry.getDefaultInstance()) return this;
      if (other.getParent() != com.google.protobuf.ByteString.EMPTY) {
        setParent(other.getParent());
      }
      if (!other.additions_.isEmpty()) {
        if (additions_.isEmpty()) {
          additions_ = other.additions_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureAdditionsIsMutable();
          additions_.addAll(other.additions_);
        }
        onChanged();
      }
      if (successorsBuilder_ == null) {
        if (!other.successors_.isEmpty()) {
          if (successors_.isEmpty()) {
            successors_ = other.successors_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureSuccessorsIsMutable();
            successors_.addAll(other.successors_);
          }
          onChanged();
        }
      } else {
        if (!other.successors_.isEmpty()) {
          if (successorsBuilder_.isEmpty()) {
            successorsBuilder_.dispose();
            successorsBuilder_ = null;
            successors_ = other.successors_;
            bitField0_ = (bitField0_ & ~0x00000004);
            successorsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSuccessorsFieldBuilder() : null;
          } else {
            successorsBuilder_.addAllMessages(other.successors_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      sawtooth.sdk.protobuf.ChangeLogEntry parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (sawtooth.sdk.protobuf.ChangeLogEntry) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.ByteString parent_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * A root hash of a merkle trie this tree was based off.
     * </pre>
     *
     * <code>bytes parent = 1;</code>
     */
    public com.google.protobuf.ByteString getParent() {
      return parent_;
    }
    /**
     * <pre>
     * A root hash of a merkle trie this tree was based off.
     * </pre>
     *
     * <code>bytes parent = 1;</code>
     */
    public Builder setParent(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      parent_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A root hash of a merkle trie this tree was based off.
     * </pre>
     *
     * <code>bytes parent = 1;</code>
     */
    public Builder clearParent() {
      
      parent_ = getDefaultInstance().getParent();
      onChanged();
      return this;
    }

    private java.util.List<com.google.protobuf.ByteString> additions_ = java.util.Collections.emptyList();
    private void ensureAdditionsIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        additions_ = new java.util.ArrayList<com.google.protobuf.ByteString>(additions_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <pre>
     * The hashes that were added for this root. These may be deleted during
     * pruning, if this root is being abandoned.
     * </pre>
     *
     * <code>repeated bytes additions = 2;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getAdditionsList() {
      return java.util.Collections.unmodifiableList(additions_);
    }
    /**
     * <pre>
     * The hashes that were added for this root. These may be deleted during
     * pruning, if this root is being abandoned.
     * </pre>
     *
     * <code>repeated bytes additions = 2;</code>
     */
    public int getAdditionsCount() {
      return additions_.size();
    }
    /**
     * <pre>
     * The hashes that were added for this root. These may be deleted during
     * pruning, if this root is being abandoned.
     * </pre>
     *
     * <code>repeated bytes additions = 2;</code>
     */
    public com.google.protobuf.ByteString getAdditions(int index) {
      return additions_.get(index);
    }
    /**
     * <pre>
     * The hashes that were added for this root. These may be deleted during
     * pruning, if this root is being abandoned.
     * </pre>
     *
     * <code>repeated bytes additions = 2;</code>
     */
    public Builder setAdditions(
        int index, com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAdditionsIsMutable();
      additions_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The hashes that were added for this root. These may be deleted during
     * pruning, if this root is being abandoned.
     * </pre>
     *
     * <code>repeated bytes additions = 2;</code>
     */
    public Builder addAdditions(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAdditionsIsMutable();
      additions_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The hashes that were added for this root. These may be deleted during
     * pruning, if this root is being abandoned.
     * </pre>
     *
     * <code>repeated bytes additions = 2;</code>
     */
    public Builder addAllAdditions(
        java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
      ensureAdditionsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, additions_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The hashes that were added for this root. These may be deleted during
     * pruning, if this root is being abandoned.
     * </pre>
     *
     * <code>repeated bytes additions = 2;</code>
     */
    public Builder clearAdditions() {
      additions_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }

    private java.util.List<sawtooth.sdk.protobuf.ChangeLogEntry.Successor> successors_ =
      java.util.Collections.emptyList();
    private void ensureSuccessorsIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        successors_ = new java.util.ArrayList<sawtooth.sdk.protobuf.ChangeLogEntry.Successor>(successors_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        sawtooth.sdk.protobuf.ChangeLogEntry.Successor, sawtooth.sdk.protobuf.ChangeLogEntry.Successor.Builder, sawtooth.sdk.protobuf.ChangeLogEntry.SuccessorOrBuilder> successorsBuilder_;

    /**
     * <pre>
     * The list of successors.
     * </pre>
     *
     * <code>repeated .ChangeLogEntry.Successor successors = 3;</code>
     */
    public java.util.List<sawtooth.sdk.protobuf.ChangeLogEntry.Successor> getSuccessorsList() {
      if (successorsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(successors_);
      } else {
        return successorsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * The list of successors.
     * </pre>
     *
     * <code>repeated .ChangeLogEntry.Successor successors = 3;</code>
     */
    public int getSuccessorsCount() {
      if (successorsBuilder_ == null) {
        return successors_.size();
      } else {
        return successorsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * The list of successors.
     * </pre>
     *
     * <code>repeated .ChangeLogEntry.Successor successors = 3;</code>
     */
    public sawtooth.sdk.protobuf.ChangeLogEntry.Successor getSuccessors(int index) {
      if (successorsBuilder_ == null) {
        return successors_.get(index);
      } else {
        return successorsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * The list of successors.
     * </pre>
     *
     * <code>repeated .ChangeLogEntry.Successor successors = 3;</code>
     */
    public Builder setSuccessors(
        int index, sawtooth.sdk.protobuf.ChangeLogEntry.Successor value) {
      if (successorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSuccessorsIsMutable();
        successors_.set(index, value);
        onChanged();
      } else {
        successorsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The list of successors.
     * </pre>
     *
     * <code>repeated .ChangeLogEntry.Successor successors = 3;</code>
     */
    public Builder setSuccessors(
        int index, sawtooth.sdk.protobuf.ChangeLogEntry.Successor.Builder builderForValue) {
      if (successorsBuilder_ == null) {
        ensureSuccessorsIsMutable();
        successors_.set(index, builderForValue.build());
        onChanged();
      } else {
        successorsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The list of successors.
     * </pre>
     *
     * <code>repeated .ChangeLogEntry.Successor successors = 3;</code>
     */
    public Builder addSuccessors(sawtooth.sdk.protobuf.ChangeLogEntry.Successor value) {
      if (successorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSuccessorsIsMutable();
        successors_.add(value);
        onChanged();
      } else {
        successorsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * The list of successors.
     * </pre>
     *
     * <code>repeated .ChangeLogEntry.Successor successors = 3;</code>
     */
    public Builder addSuccessors(
        int index, sawtooth.sdk.protobuf.ChangeLogEntry.Successor value) {
      if (successorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSuccessorsIsMutable();
        successors_.add(index, value);
        onChanged();
      } else {
        successorsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The list of successors.
     * </pre>
     *
     * <code>repeated .ChangeLogEntry.Successor successors = 3;</code>
     */
    public Builder addSuccessors(
        sawtooth.sdk.protobuf.ChangeLogEntry.Successor.Builder builderForValue) {
      if (successorsBuilder_ == null) {
        ensureSuccessorsIsMutable();
        successors_.add(builderForValue.build());
        onChanged();
      } else {
        successorsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The list of successors.
     * </pre>
     *
     * <code>repeated .ChangeLogEntry.Successor successors = 3;</code>
     */
    public Builder addSuccessors(
        int index, sawtooth.sdk.protobuf.ChangeLogEntry.Successor.Builder builderForValue) {
      if (successorsBuilder_ == null) {
        ensureSuccessorsIsMutable();
        successors_.add(index, builderForValue.build());
        onChanged();
      } else {
        successorsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The list of successors.
     * </pre>
     *
     * <code>repeated .ChangeLogEntry.Successor successors = 3;</code>
     */
    public Builder addAllSuccessors(
        java.lang.Iterable<? extends sawtooth.sdk.protobuf.ChangeLogEntry.Successor> values) {
      if (successorsBuilder_ == null) {
        ensureSuccessorsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, successors_);
        onChanged();
      } else {
        successorsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * The list of successors.
     * </pre>
     *
     * <code>repeated .ChangeLogEntry.Successor successors = 3;</code>
     */
    public Builder clearSuccessors() {
      if (successorsBuilder_ == null) {
        successors_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        successorsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The list of successors.
     * </pre>
     *
     * <code>repeated .ChangeLogEntry.Successor successors = 3;</code>
     */
    public Builder removeSuccessors(int index) {
      if (successorsBuilder_ == null) {
        ensureSuccessorsIsMutable();
        successors_.remove(index);
        onChanged();
      } else {
        successorsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * The list of successors.
     * </pre>
     *
     * <code>repeated .ChangeLogEntry.Successor successors = 3;</code>
     */
    public sawtooth.sdk.protobuf.ChangeLogEntry.Successor.Builder getSuccessorsBuilder(
        int index) {
      return getSuccessorsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * The list of successors.
     * </pre>
     *
     * <code>repeated .ChangeLogEntry.Successor successors = 3;</code>
     */
    public sawtooth.sdk.protobuf.ChangeLogEntry.SuccessorOrBuilder getSuccessorsOrBuilder(
        int index) {
      if (successorsBuilder_ == null) {
        return successors_.get(index);  } else {
        return successorsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * The list of successors.
     * </pre>
     *
     * <code>repeated .ChangeLogEntry.Successor successors = 3;</code>
     */
    public java.util.List<? extends sawtooth.sdk.protobuf.ChangeLogEntry.SuccessorOrBuilder> 
         getSuccessorsOrBuilderList() {
      if (successorsBuilder_ != null) {
        return successorsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(successors_);
      }
    }
    /**
     * <pre>
     * The list of successors.
     * </pre>
     *
     * <code>repeated .ChangeLogEntry.Successor successors = 3;</code>
     */
    public sawtooth.sdk.protobuf.ChangeLogEntry.Successor.Builder addSuccessorsBuilder() {
      return getSuccessorsFieldBuilder().addBuilder(
          sawtooth.sdk.protobuf.ChangeLogEntry.Successor.getDefaultInstance());
    }
    /**
     * <pre>
     * The list of successors.
     * </pre>
     *
     * <code>repeated .ChangeLogEntry.Successor successors = 3;</code>
     */
    public sawtooth.sdk.protobuf.ChangeLogEntry.Successor.Builder addSuccessorsBuilder(
        int index) {
      return getSuccessorsFieldBuilder().addBuilder(
          index, sawtooth.sdk.protobuf.ChangeLogEntry.Successor.getDefaultInstance());
    }
    /**
     * <pre>
     * The list of successors.
     * </pre>
     *
     * <code>repeated .ChangeLogEntry.Successor successors = 3;</code>
     */
    public java.util.List<sawtooth.sdk.protobuf.ChangeLogEntry.Successor.Builder> 
         getSuccessorsBuilderList() {
      return getSuccessorsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        sawtooth.sdk.protobuf.ChangeLogEntry.Successor, sawtooth.sdk.protobuf.ChangeLogEntry.Successor.Builder, sawtooth.sdk.protobuf.ChangeLogEntry.SuccessorOrBuilder> 
        getSuccessorsFieldBuilder() {
      if (successorsBuilder_ == null) {
        successorsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            sawtooth.sdk.protobuf.ChangeLogEntry.Successor, sawtooth.sdk.protobuf.ChangeLogEntry.Successor.Builder, sawtooth.sdk.protobuf.ChangeLogEntry.SuccessorOrBuilder>(
                successors_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        successors_ = null;
      }
      return successorsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ChangeLogEntry)
  }

  // @@protoc_insertion_point(class_scope:ChangeLogEntry)
  private static final sawtooth.sdk.protobuf.ChangeLogEntry DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new sawtooth.sdk.protobuf.ChangeLogEntry();
  }

  public static sawtooth.sdk.protobuf.ChangeLogEntry getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChangeLogEntry>
      PARSER = new com.google.protobuf.AbstractParser<ChangeLogEntry>() {
    @java.lang.Override
    public ChangeLogEntry parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ChangeLogEntry(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ChangeLogEntry> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChangeLogEntry> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public sawtooth.sdk.protobuf.ChangeLogEntry getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

