// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_event.proto

package sawtooth.sdk.protobuf;

public interface ClientEventsGetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClientEventsGetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .EventSubscription subscriptions = 1;</code>
   */
  java.util.List<sawtooth.sdk.protobuf.EventSubscription> 
      getSubscriptionsList();
  /**
   * <code>repeated .EventSubscription subscriptions = 1;</code>
   */
  sawtooth.sdk.protobuf.EventSubscription getSubscriptions(int index);
  /**
   * <code>repeated .EventSubscription subscriptions = 1;</code>
   */
  int getSubscriptionsCount();
  /**
   * <code>repeated .EventSubscription subscriptions = 1;</code>
   */
  java.util.List<? extends sawtooth.sdk.protobuf.EventSubscriptionOrBuilder> 
      getSubscriptionsOrBuilderList();
  /**
   * <code>repeated .EventSubscription subscriptions = 1;</code>
   */
  sawtooth.sdk.protobuf.EventSubscriptionOrBuilder getSubscriptionsOrBuilder(
      int index);

  /**
   * <code>repeated string block_ids = 2;</code>
   */
  java.util.List<java.lang.String>
      getBlockIdsList();
  /**
   * <code>repeated string block_ids = 2;</code>
   */
  int getBlockIdsCount();
  /**
   * <code>repeated string block_ids = 2;</code>
   */
  java.lang.String getBlockIds(int index);
  /**
   * <code>repeated string block_ids = 2;</code>
   */
  com.google.protobuf.ByteString
      getBlockIdsBytes(int index);
}
