// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_event.proto

package sawtooth.sdk.protobuf;

/**
 * Protobuf type {@code ClientEventsGetRequest}
 */
public  final class ClientEventsGetRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ClientEventsGetRequest)
    ClientEventsGetRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ClientEventsGetRequest.newBuilder() to construct.
  private ClientEventsGetRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ClientEventsGetRequest() {
    subscriptions_ = java.util.Collections.emptyList();
    blockIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ClientEventsGetRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              subscriptions_ = new java.util.ArrayList<sawtooth.sdk.protobuf.EventSubscription>();
              mutable_bitField0_ |= 0x00000001;
            }
            subscriptions_.add(
                input.readMessage(sawtooth.sdk.protobuf.EventSubscription.parser(), extensionRegistry));
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              blockIds_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            blockIds_.add(s);
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        subscriptions_ = java.util.Collections.unmodifiableList(subscriptions_);
      }
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        blockIds_ = blockIds_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return sawtooth.sdk.protobuf.ClientEvent.internal_static_ClientEventsGetRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return sawtooth.sdk.protobuf.ClientEvent.internal_static_ClientEventsGetRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            sawtooth.sdk.protobuf.ClientEventsGetRequest.class, sawtooth.sdk.protobuf.ClientEventsGetRequest.Builder.class);
  }

  public static final int SUBSCRIPTIONS_FIELD_NUMBER = 1;
  private java.util.List<sawtooth.sdk.protobuf.EventSubscription> subscriptions_;
  /**
   * <code>repeated .EventSubscription subscriptions = 1;</code>
   */
  public java.util.List<sawtooth.sdk.protobuf.EventSubscription> getSubscriptionsList() {
    return subscriptions_;
  }
  /**
   * <code>repeated .EventSubscription subscriptions = 1;</code>
   */
  public java.util.List<? extends sawtooth.sdk.protobuf.EventSubscriptionOrBuilder> 
      getSubscriptionsOrBuilderList() {
    return subscriptions_;
  }
  /**
   * <code>repeated .EventSubscription subscriptions = 1;</code>
   */
  public int getSubscriptionsCount() {
    return subscriptions_.size();
  }
  /**
   * <code>repeated .EventSubscription subscriptions = 1;</code>
   */
  public sawtooth.sdk.protobuf.EventSubscription getSubscriptions(int index) {
    return subscriptions_.get(index);
  }
  /**
   * <code>repeated .EventSubscription subscriptions = 1;</code>
   */
  public sawtooth.sdk.protobuf.EventSubscriptionOrBuilder getSubscriptionsOrBuilder(
      int index) {
    return subscriptions_.get(index);
  }

  public static final int BLOCK_IDS_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList blockIds_;
  /**
   * <code>repeated string block_ids = 2;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getBlockIdsList() {
    return blockIds_;
  }
  /**
   * <code>repeated string block_ids = 2;</code>
   */
  public int getBlockIdsCount() {
    return blockIds_.size();
  }
  /**
   * <code>repeated string block_ids = 2;</code>
   */
  public java.lang.String getBlockIds(int index) {
    return blockIds_.get(index);
  }
  /**
   * <code>repeated string block_ids = 2;</code>
   */
  public com.google.protobuf.ByteString
      getBlockIdsBytes(int index) {
    return blockIds_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < subscriptions_.size(); i++) {
      output.writeMessage(1, subscriptions_.get(i));
    }
    for (int i = 0; i < blockIds_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, blockIds_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < subscriptions_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, subscriptions_.get(i));
    }
    {
      int dataSize = 0;
      for (int i = 0; i < blockIds_.size(); i++) {
        dataSize += computeStringSizeNoTag(blockIds_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getBlockIdsList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof sawtooth.sdk.protobuf.ClientEventsGetRequest)) {
      return super.equals(obj);
    }
    sawtooth.sdk.protobuf.ClientEventsGetRequest other = (sawtooth.sdk.protobuf.ClientEventsGetRequest) obj;

    boolean result = true;
    result = result && getSubscriptionsList()
        .equals(other.getSubscriptionsList());
    result = result && getBlockIdsList()
        .equals(other.getBlockIdsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getSubscriptionsCount() > 0) {
      hash = (37 * hash) + SUBSCRIPTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getSubscriptionsList().hashCode();
    }
    if (getBlockIdsCount() > 0) {
      hash = (37 * hash) + BLOCK_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getBlockIdsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static sawtooth.sdk.protobuf.ClientEventsGetRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sawtooth.sdk.protobuf.ClientEventsGetRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sawtooth.sdk.protobuf.ClientEventsGetRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sawtooth.sdk.protobuf.ClientEventsGetRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sawtooth.sdk.protobuf.ClientEventsGetRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sawtooth.sdk.protobuf.ClientEventsGetRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sawtooth.sdk.protobuf.ClientEventsGetRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sawtooth.sdk.protobuf.ClientEventsGetRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static sawtooth.sdk.protobuf.ClientEventsGetRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static sawtooth.sdk.protobuf.ClientEventsGetRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static sawtooth.sdk.protobuf.ClientEventsGetRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sawtooth.sdk.protobuf.ClientEventsGetRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sawtooth.sdk.protobuf.ClientEventsGetRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ClientEventsGetRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ClientEventsGetRequest)
      sawtooth.sdk.protobuf.ClientEventsGetRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sawtooth.sdk.protobuf.ClientEvent.internal_static_ClientEventsGetRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sawtooth.sdk.protobuf.ClientEvent.internal_static_ClientEventsGetRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sawtooth.sdk.protobuf.ClientEventsGetRequest.class, sawtooth.sdk.protobuf.ClientEventsGetRequest.Builder.class);
    }

    // Construct using sawtooth.sdk.protobuf.ClientEventsGetRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSubscriptionsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (subscriptionsBuilder_ == null) {
        subscriptions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        subscriptionsBuilder_.clear();
      }
      blockIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return sawtooth.sdk.protobuf.ClientEvent.internal_static_ClientEventsGetRequest_descriptor;
    }

    @java.lang.Override
    public sawtooth.sdk.protobuf.ClientEventsGetRequest getDefaultInstanceForType() {
      return sawtooth.sdk.protobuf.ClientEventsGetRequest.getDefaultInstance();
    }

    @java.lang.Override
    public sawtooth.sdk.protobuf.ClientEventsGetRequest build() {
      sawtooth.sdk.protobuf.ClientEventsGetRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public sawtooth.sdk.protobuf.ClientEventsGetRequest buildPartial() {
      sawtooth.sdk.protobuf.ClientEventsGetRequest result = new sawtooth.sdk.protobuf.ClientEventsGetRequest(this);
      int from_bitField0_ = bitField0_;
      if (subscriptionsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          subscriptions_ = java.util.Collections.unmodifiableList(subscriptions_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.subscriptions_ = subscriptions_;
      } else {
        result.subscriptions_ = subscriptionsBuilder_.build();
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        blockIds_ = blockIds_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.blockIds_ = blockIds_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof sawtooth.sdk.protobuf.ClientEventsGetRequest) {
        return mergeFrom((sawtooth.sdk.protobuf.ClientEventsGetRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(sawtooth.sdk.protobuf.ClientEventsGetRequest other) {
      if (other == sawtooth.sdk.protobuf.ClientEventsGetRequest.getDefaultInstance()) return this;
      if (subscriptionsBuilder_ == null) {
        if (!other.subscriptions_.isEmpty()) {
          if (subscriptions_.isEmpty()) {
            subscriptions_ = other.subscriptions_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSubscriptionsIsMutable();
            subscriptions_.addAll(other.subscriptions_);
          }
          onChanged();
        }
      } else {
        if (!other.subscriptions_.isEmpty()) {
          if (subscriptionsBuilder_.isEmpty()) {
            subscriptionsBuilder_.dispose();
            subscriptionsBuilder_ = null;
            subscriptions_ = other.subscriptions_;
            bitField0_ = (bitField0_ & ~0x00000001);
            subscriptionsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSubscriptionsFieldBuilder() : null;
          } else {
            subscriptionsBuilder_.addAllMessages(other.subscriptions_);
          }
        }
      }
      if (!other.blockIds_.isEmpty()) {
        if (blockIds_.isEmpty()) {
          blockIds_ = other.blockIds_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureBlockIdsIsMutable();
          blockIds_.addAll(other.blockIds_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      sawtooth.sdk.protobuf.ClientEventsGetRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (sawtooth.sdk.protobuf.ClientEventsGetRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<sawtooth.sdk.protobuf.EventSubscription> subscriptions_ =
      java.util.Collections.emptyList();
    private void ensureSubscriptionsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        subscriptions_ = new java.util.ArrayList<sawtooth.sdk.protobuf.EventSubscription>(subscriptions_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        sawtooth.sdk.protobuf.EventSubscription, sawtooth.sdk.protobuf.EventSubscription.Builder, sawtooth.sdk.protobuf.EventSubscriptionOrBuilder> subscriptionsBuilder_;

    /**
     * <code>repeated .EventSubscription subscriptions = 1;</code>
     */
    public java.util.List<sawtooth.sdk.protobuf.EventSubscription> getSubscriptionsList() {
      if (subscriptionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(subscriptions_);
      } else {
        return subscriptionsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .EventSubscription subscriptions = 1;</code>
     */
    public int getSubscriptionsCount() {
      if (subscriptionsBuilder_ == null) {
        return subscriptions_.size();
      } else {
        return subscriptionsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .EventSubscription subscriptions = 1;</code>
     */
    public sawtooth.sdk.protobuf.EventSubscription getSubscriptions(int index) {
      if (subscriptionsBuilder_ == null) {
        return subscriptions_.get(index);
      } else {
        return subscriptionsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .EventSubscription subscriptions = 1;</code>
     */
    public Builder setSubscriptions(
        int index, sawtooth.sdk.protobuf.EventSubscription value) {
      if (subscriptionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSubscriptionsIsMutable();
        subscriptions_.set(index, value);
        onChanged();
      } else {
        subscriptionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .EventSubscription subscriptions = 1;</code>
     */
    public Builder setSubscriptions(
        int index, sawtooth.sdk.protobuf.EventSubscription.Builder builderForValue) {
      if (subscriptionsBuilder_ == null) {
        ensureSubscriptionsIsMutable();
        subscriptions_.set(index, builderForValue.build());
        onChanged();
      } else {
        subscriptionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .EventSubscription subscriptions = 1;</code>
     */
    public Builder addSubscriptions(sawtooth.sdk.protobuf.EventSubscription value) {
      if (subscriptionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSubscriptionsIsMutable();
        subscriptions_.add(value);
        onChanged();
      } else {
        subscriptionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .EventSubscription subscriptions = 1;</code>
     */
    public Builder addSubscriptions(
        int index, sawtooth.sdk.protobuf.EventSubscription value) {
      if (subscriptionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSubscriptionsIsMutable();
        subscriptions_.add(index, value);
        onChanged();
      } else {
        subscriptionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .EventSubscription subscriptions = 1;</code>
     */
    public Builder addSubscriptions(
        sawtooth.sdk.protobuf.EventSubscription.Builder builderForValue) {
      if (subscriptionsBuilder_ == null) {
        ensureSubscriptionsIsMutable();
        subscriptions_.add(builderForValue.build());
        onChanged();
      } else {
        subscriptionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .EventSubscription subscriptions = 1;</code>
     */
    public Builder addSubscriptions(
        int index, sawtooth.sdk.protobuf.EventSubscription.Builder builderForValue) {
      if (subscriptionsBuilder_ == null) {
        ensureSubscriptionsIsMutable();
        subscriptions_.add(index, builderForValue.build());
        onChanged();
      } else {
        subscriptionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .EventSubscription subscriptions = 1;</code>
     */
    public Builder addAllSubscriptions(
        java.lang.Iterable<? extends sawtooth.sdk.protobuf.EventSubscription> values) {
      if (subscriptionsBuilder_ == null) {
        ensureSubscriptionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, subscriptions_);
        onChanged();
      } else {
        subscriptionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .EventSubscription subscriptions = 1;</code>
     */
    public Builder clearSubscriptions() {
      if (subscriptionsBuilder_ == null) {
        subscriptions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        subscriptionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .EventSubscription subscriptions = 1;</code>
     */
    public Builder removeSubscriptions(int index) {
      if (subscriptionsBuilder_ == null) {
        ensureSubscriptionsIsMutable();
        subscriptions_.remove(index);
        onChanged();
      } else {
        subscriptionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .EventSubscription subscriptions = 1;</code>
     */
    public sawtooth.sdk.protobuf.EventSubscription.Builder getSubscriptionsBuilder(
        int index) {
      return getSubscriptionsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .EventSubscription subscriptions = 1;</code>
     */
    public sawtooth.sdk.protobuf.EventSubscriptionOrBuilder getSubscriptionsOrBuilder(
        int index) {
      if (subscriptionsBuilder_ == null) {
        return subscriptions_.get(index);  } else {
        return subscriptionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .EventSubscription subscriptions = 1;</code>
     */
    public java.util.List<? extends sawtooth.sdk.protobuf.EventSubscriptionOrBuilder> 
         getSubscriptionsOrBuilderList() {
      if (subscriptionsBuilder_ != null) {
        return subscriptionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(subscriptions_);
      }
    }
    /**
     * <code>repeated .EventSubscription subscriptions = 1;</code>
     */
    public sawtooth.sdk.protobuf.EventSubscription.Builder addSubscriptionsBuilder() {
      return getSubscriptionsFieldBuilder().addBuilder(
          sawtooth.sdk.protobuf.EventSubscription.getDefaultInstance());
    }
    /**
     * <code>repeated .EventSubscription subscriptions = 1;</code>
     */
    public sawtooth.sdk.protobuf.EventSubscription.Builder addSubscriptionsBuilder(
        int index) {
      return getSubscriptionsFieldBuilder().addBuilder(
          index, sawtooth.sdk.protobuf.EventSubscription.getDefaultInstance());
    }
    /**
     * <code>repeated .EventSubscription subscriptions = 1;</code>
     */
    public java.util.List<sawtooth.sdk.protobuf.EventSubscription.Builder> 
         getSubscriptionsBuilderList() {
      return getSubscriptionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        sawtooth.sdk.protobuf.EventSubscription, sawtooth.sdk.protobuf.EventSubscription.Builder, sawtooth.sdk.protobuf.EventSubscriptionOrBuilder> 
        getSubscriptionsFieldBuilder() {
      if (subscriptionsBuilder_ == null) {
        subscriptionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            sawtooth.sdk.protobuf.EventSubscription, sawtooth.sdk.protobuf.EventSubscription.Builder, sawtooth.sdk.protobuf.EventSubscriptionOrBuilder>(
                subscriptions_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        subscriptions_ = null;
      }
      return subscriptionsBuilder_;
    }

    private com.google.protobuf.LazyStringList blockIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureBlockIdsIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        blockIds_ = new com.google.protobuf.LazyStringArrayList(blockIds_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated string block_ids = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getBlockIdsList() {
      return blockIds_.getUnmodifiableView();
    }
    /**
     * <code>repeated string block_ids = 2;</code>
     */
    public int getBlockIdsCount() {
      return blockIds_.size();
    }
    /**
     * <code>repeated string block_ids = 2;</code>
     */
    public java.lang.String getBlockIds(int index) {
      return blockIds_.get(index);
    }
    /**
     * <code>repeated string block_ids = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBlockIdsBytes(int index) {
      return blockIds_.getByteString(index);
    }
    /**
     * <code>repeated string block_ids = 2;</code>
     */
    public Builder setBlockIds(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureBlockIdsIsMutable();
      blockIds_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string block_ids = 2;</code>
     */
    public Builder addBlockIds(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureBlockIdsIsMutable();
      blockIds_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string block_ids = 2;</code>
     */
    public Builder addAllBlockIds(
        java.lang.Iterable<java.lang.String> values) {
      ensureBlockIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, blockIds_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string block_ids = 2;</code>
     */
    public Builder clearBlockIds() {
      blockIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string block_ids = 2;</code>
     */
    public Builder addBlockIdsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureBlockIdsIsMutable();
      blockIds_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ClientEventsGetRequest)
  }

  // @@protoc_insertion_point(class_scope:ClientEventsGetRequest)
  private static final sawtooth.sdk.protobuf.ClientEventsGetRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new sawtooth.sdk.protobuf.ClientEventsGetRequest();
  }

  public static sawtooth.sdk.protobuf.ClientEventsGetRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClientEventsGetRequest>
      PARSER = new com.google.protobuf.AbstractParser<ClientEventsGetRequest>() {
    @java.lang.Override
    public ClientEventsGetRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ClientEventsGetRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ClientEventsGetRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClientEventsGetRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public sawtooth.sdk.protobuf.ClientEventsGetRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

