// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_block.proto

package sawtooth.sdk.protobuf;

public interface ClientBlockListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClientBlockListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ClientBlockListResponse.Status status = 1;</code>
   */
  int getStatusValue();
  /**
   * <code>.ClientBlockListResponse.Status status = 1;</code>
   */
  sawtooth.sdk.protobuf.ClientBlockListResponse.Status getStatus();

  /**
   * <code>repeated .Block blocks = 2;</code>
   */
  java.util.List<sawtooth.sdk.protobuf.Block> 
      getBlocksList();
  /**
   * <code>repeated .Block blocks = 2;</code>
   */
  sawtooth.sdk.protobuf.Block getBlocks(int index);
  /**
   * <code>repeated .Block blocks = 2;</code>
   */
  int getBlocksCount();
  /**
   * <code>repeated .Block blocks = 2;</code>
   */
  java.util.List<? extends sawtooth.sdk.protobuf.BlockOrBuilder> 
      getBlocksOrBuilderList();
  /**
   * <code>repeated .Block blocks = 2;</code>
   */
  sawtooth.sdk.protobuf.BlockOrBuilder getBlocksOrBuilder(
      int index);

  /**
   * <code>string head_id = 3;</code>
   */
  java.lang.String getHeadId();
  /**
   * <code>string head_id = 3;</code>
   */
  com.google.protobuf.ByteString
      getHeadIdBytes();

  /**
   * <code>.ClientPagingResponse paging = 4;</code>
   */
  boolean hasPaging();
  /**
   * <code>.ClientPagingResponse paging = 4;</code>
   */
  sawtooth.sdk.protobuf.ClientPagingResponse getPaging();
  /**
   * <code>.ClientPagingResponse paging = 4;</code>
   */
  sawtooth.sdk.protobuf.ClientPagingResponseOrBuilder getPagingOrBuilder();
}
