// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_batch.proto

package sawtooth.sdk.protobuf;

public interface ClientBatchListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClientBatchListRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string head_id = 1;</code>
   */
  java.lang.String getHeadId();
  /**
   * <code>string head_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getHeadIdBytes();

  /**
   * <code>repeated string batch_ids = 2;</code>
   */
  java.util.List<java.lang.String>
      getBatchIdsList();
  /**
   * <code>repeated string batch_ids = 2;</code>
   */
  int getBatchIdsCount();
  /**
   * <code>repeated string batch_ids = 2;</code>
   */
  java.lang.String getBatchIds(int index);
  /**
   * <code>repeated string batch_ids = 2;</code>
   */
  com.google.protobuf.ByteString
      getBatchIdsBytes(int index);

  /**
   * <code>.ClientPagingControls paging = 3;</code>
   */
  boolean hasPaging();
  /**
   * <code>.ClientPagingControls paging = 3;</code>
   */
  sawtooth.sdk.protobuf.ClientPagingControls getPaging();
  /**
   * <code>.ClientPagingControls paging = 3;</code>
   */
  sawtooth.sdk.protobuf.ClientPagingControlsOrBuilder getPagingOrBuilder();

  /**
   * <code>repeated .ClientSortControls sorting = 4;</code>
   */
  java.util.List<sawtooth.sdk.protobuf.ClientSortControls> 
      getSortingList();
  /**
   * <code>repeated .ClientSortControls sorting = 4;</code>
   */
  sawtooth.sdk.protobuf.ClientSortControls getSorting(int index);
  /**
   * <code>repeated .ClientSortControls sorting = 4;</code>
   */
  int getSortingCount();
  /**
   * <code>repeated .ClientSortControls sorting = 4;</code>
   */
  java.util.List<? extends sawtooth.sdk.protobuf.ClientSortControlsOrBuilder> 
      getSortingOrBuilderList();
  /**
   * <code>repeated .ClientSortControls sorting = 4;</code>
   */
  sawtooth.sdk.protobuf.ClientSortControlsOrBuilder getSortingOrBuilder(
      int index);
}
