// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_batch_submit.proto

package sawtooth.sdk.protobuf;

public interface ClientBatchSubmitRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClientBatchSubmitRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Batch batches = 1;</code>
   */
  java.util.List<sawtooth.sdk.protobuf.Batch> 
      getBatchesList();
  /**
   * <code>repeated .Batch batches = 1;</code>
   */
  sawtooth.sdk.protobuf.Batch getBatches(int index);
  /**
   * <code>repeated .Batch batches = 1;</code>
   */
  int getBatchesCount();
  /**
   * <code>repeated .Batch batches = 1;</code>
   */
  java.util.List<? extends sawtooth.sdk.protobuf.BatchOrBuilder> 
      getBatchesOrBuilderList();
  /**
   * <code>repeated .Batch batches = 1;</code>
   */
  sawtooth.sdk.protobuf.BatchOrBuilder getBatchesOrBuilder(
      int index);
}
