// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_block.proto

package sawtooth.sdk.protobuf;

public interface ClientBlockGetByBatchIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClientBlockGetByBatchIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string batch_id = 1;</code>
   */
  java.lang.String getBatchId();
  /**
   * <code>string batch_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getBatchIdBytes();
}
