// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_batch_submit.proto

package sawtooth.sdk.protobuf;

public interface ClientBatchStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClientBatchStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string batch_id = 1;</code>
   */
  java.lang.String getBatchId();
  /**
   * <code>string batch_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getBatchIdBytes();

  /**
   * <code>.ClientBatchStatus.Status status = 2;</code>
   */
  int getStatusValue();
  /**
   * <code>.ClientBatchStatus.Status status = 2;</code>
   */
  sawtooth.sdk.protobuf.ClientBatchStatus.Status getStatus();

  /**
   * <code>repeated .ClientBatchStatus.InvalidTransaction invalid_transactions = 3;</code>
   */
  java.util.List<sawtooth.sdk.protobuf.ClientBatchStatus.InvalidTransaction> 
      getInvalidTransactionsList();
  /**
   * <code>repeated .ClientBatchStatus.InvalidTransaction invalid_transactions = 3;</code>
   */
  sawtooth.sdk.protobuf.ClientBatchStatus.InvalidTransaction getInvalidTransactions(int index);
  /**
   * <code>repeated .ClientBatchStatus.InvalidTransaction invalid_transactions = 3;</code>
   */
  int getInvalidTransactionsCount();
  /**
   * <code>repeated .ClientBatchStatus.InvalidTransaction invalid_transactions = 3;</code>
   */
  java.util.List<? extends sawtooth.sdk.protobuf.ClientBatchStatus.InvalidTransactionOrBuilder> 
      getInvalidTransactionsOrBuilderList();
  /**
   * <code>repeated .ClientBatchStatus.InvalidTransaction invalid_transactions = 3;</code>
   */
  sawtooth.sdk.protobuf.ClientBatchStatus.InvalidTransactionOrBuilder getInvalidTransactionsOrBuilder(
      int index);
}
