// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_batch_submit.proto

package sawtooth.sdk.protobuf;

public interface ClientBatchStatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClientBatchStatusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string batch_ids = 1;</code>
   */
  java.util.List<java.lang.String>
      getBatchIdsList();
  /**
   * <code>repeated string batch_ids = 1;</code>
   */
  int getBatchIdsCount();
  /**
   * <code>repeated string batch_ids = 1;</code>
   */
  java.lang.String getBatchIds(int index);
  /**
   * <code>repeated string batch_ids = 1;</code>
   */
  com.google.protobuf.ByteString
      getBatchIdsBytes(int index);

  /**
   * <code>bool wait = 2;</code>
   */
  boolean getWait();

  /**
   * <code>uint32 timeout = 3;</code>
   */
  int getTimeout();
}
