// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_batch_submit.proto

package sawtooth.sdk.protobuf;

public final class ClientBatchSubmit {
  private ClientBatchSubmit() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientBatchStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientBatchStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientBatchStatus_InvalidTransaction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientBatchStatus_InvalidTransaction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientBatchSubmitRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientBatchSubmitRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientBatchSubmitResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientBatchSubmitResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientBatchStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientBatchStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientBatchStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientBatchStatusResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031client_batch_submit.proto\032\013batch.proto" +
      "\"\275\002\n\021ClientBatchStatus\022\020\n\010batch_id\030\001 \001(\t" +
      "\022)\n\006status\030\002 \001(\0162\031.ClientBatchStatus.Sta" +
      "tus\022C\n\024invalid_transactions\030\003 \003(\0132%.Clie" +
      "ntBatchStatus.InvalidTransaction\032T\n\022Inva" +
      "lidTransaction\022\026\n\016transaction_id\030\001 \001(\t\022\017" +
      "\n\007message\030\002 \001(\t\022\025\n\rextended_data\030\003 \001(\014\"P" +
      "\n\006Status\022\020\n\014STATUS_UNSET\020\000\022\r\n\tCOMMITTED\020" +
      "\001\022\013\n\007INVALID\020\002\022\013\n\007PENDING\020\003\022\013\n\007UNKNOWN\020\004" +
      "\"3\n\030ClientBatchSubmitRequest\022\027\n\007batches\030" +
      "\001 \003(\0132\006.Batch\"\251\001\n\031ClientBatchSubmitRespo" +
      "nse\0221\n\006status\030\001 \001(\0162!.ClientBatchSubmitR" +
      "esponse.Status\"Y\n\006Status\022\020\n\014STATUS_UNSET" +
      "\020\000\022\006\n\002OK\020\001\022\022\n\016INTERNAL_ERROR\020\002\022\021\n\rINVALI" +
      "D_BATCH\020\003\022\016\n\nQUEUE_FULL\020\004\"L\n\030ClientBatch" +
      "StatusRequest\022\021\n\tbatch_ids\030\001 \003(\t\022\014\n\004wait" +
      "\030\002 \001(\010\022\017\n\007timeout\030\003 \001(\r\"\323\001\n\031ClientBatchS" +
      "tatusResponse\0221\n\006status\030\001 \001(\0162!.ClientBa" +
      "tchStatusResponse.Status\022*\n\016batch_status" +
      "es\030\002 \003(\0132\022.ClientBatchStatus\"W\n\006Status\022\020" +
      "\n\014STATUS_UNSET\020\000\022\006\n\002OK\020\001\022\022\n\016INTERNAL_ERR" +
      "OR\020\002\022\017\n\013NO_RESOURCE\020\005\022\016\n\nINVALID_ID\020\010B2\n" +
      "\025sawtooth.sdk.protobufP\001Z\027client_batch_s" +
      "ubmit_pb2b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          sawtooth.sdk.protobuf.BatchOuterClass.getDescriptor(),
        }, assigner);
    internal_static_ClientBatchStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ClientBatchStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientBatchStatus_descriptor,
        new java.lang.String[] { "BatchId", "Status", "InvalidTransactions", });
    internal_static_ClientBatchStatus_InvalidTransaction_descriptor =
      internal_static_ClientBatchStatus_descriptor.getNestedTypes().get(0);
    internal_static_ClientBatchStatus_InvalidTransaction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientBatchStatus_InvalidTransaction_descriptor,
        new java.lang.String[] { "TransactionId", "Message", "ExtendedData", });
    internal_static_ClientBatchSubmitRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ClientBatchSubmitRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientBatchSubmitRequest_descriptor,
        new java.lang.String[] { "Batches", });
    internal_static_ClientBatchSubmitResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ClientBatchSubmitResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientBatchSubmitResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_ClientBatchStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ClientBatchStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientBatchStatusRequest_descriptor,
        new java.lang.String[] { "BatchIds", "Wait", "Timeout", });
    internal_static_ClientBatchStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ClientBatchStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientBatchStatusResponse_descriptor,
        new java.lang.String[] { "Status", "BatchStatuses", });
    sawtooth.sdk.protobuf.BatchOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
