// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_batch_submit.proto

package sawtooth.sdk.protobuf;

public interface ClientBatchStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClientBatchStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ClientBatchStatusResponse.Status status = 1;</code>
   */
  int getStatusValue();
  /**
   * <code>.ClientBatchStatusResponse.Status status = 1;</code>
   */
  sawtooth.sdk.protobuf.ClientBatchStatusResponse.Status getStatus();

  /**
   * <code>repeated .ClientBatchStatus batch_statuses = 2;</code>
   */
  java.util.List<sawtooth.sdk.protobuf.ClientBatchStatus> 
      getBatchStatusesList();
  /**
   * <code>repeated .ClientBatchStatus batch_statuses = 2;</code>
   */
  sawtooth.sdk.protobuf.ClientBatchStatus getBatchStatuses(int index);
  /**
   * <code>repeated .ClientBatchStatus batch_statuses = 2;</code>
   */
  int getBatchStatusesCount();
  /**
   * <code>repeated .ClientBatchStatus batch_statuses = 2;</code>
   */
  java.util.List<? extends sawtooth.sdk.protobuf.ClientBatchStatusOrBuilder> 
      getBatchStatusesOrBuilderList();
  /**
   * <code>repeated .ClientBatchStatus batch_statuses = 2;</code>
   */
  sawtooth.sdk.protobuf.ClientBatchStatusOrBuilder getBatchStatusesOrBuilder(
      int index);
}
