// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_receipt.proto

package sawtooth.sdk.protobuf;

public interface ClientReceiptGetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClientReceiptGetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ClientReceiptGetResponse.Status status = 1;</code>
   */
  int getStatusValue();
  /**
   * <code>.ClientReceiptGetResponse.Status status = 1;</code>
   */
  sawtooth.sdk.protobuf.ClientReceiptGetResponse.Status getStatus();

  /**
   * <code>repeated .TransactionReceipt receipts = 2;</code>
   */
  java.util.List<sawtooth.sdk.protobuf.TransactionReceipt> 
      getReceiptsList();
  /**
   * <code>repeated .TransactionReceipt receipts = 2;</code>
   */
  sawtooth.sdk.protobuf.TransactionReceipt getReceipts(int index);
  /**
   * <code>repeated .TransactionReceipt receipts = 2;</code>
   */
  int getReceiptsCount();
  /**
   * <code>repeated .TransactionReceipt receipts = 2;</code>
   */
  java.util.List<? extends sawtooth.sdk.protobuf.TransactionReceiptOrBuilder> 
      getReceiptsOrBuilderList();
  /**
   * <code>repeated .TransactionReceipt receipts = 2;</code>
   */
  sawtooth.sdk.protobuf.TransactionReceiptOrBuilder getReceiptsOrBuilder(
      int index);
}
