// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_peers.proto

package sawtooth.sdk.protobuf;

public interface ClientPeersGetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClientPeersGetRequest)
    com.google.protobuf.MessageOrBuilder {
}
