// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_block.proto

package sawtooth.sdk.protobuf;

public interface ClientBlockGetByTransactionIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClientBlockGetByTransactionIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string transaction_id = 1;</code>
   */
  java.lang.String getTransactionId();
  /**
   * <code>string transaction_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getTransactionIdBytes();
}
