// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_batch.proto

package sawtooth.sdk.protobuf;

public interface ClientBatchGetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClientBatchGetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ClientBatchGetResponse.Status status = 1;</code>
   */
  int getStatusValue();
  /**
   * <code>.ClientBatchGetResponse.Status status = 1;</code>
   */
  sawtooth.sdk.protobuf.ClientBatchGetResponse.Status getStatus();

  /**
   * <code>.Batch batch = 2;</code>
   */
  boolean hasBatch();
  /**
   * <code>.Batch batch = 2;</code>
   */
  sawtooth.sdk.protobuf.Batch getBatch();
  /**
   * <code>.Batch batch = 2;</code>
   */
  sawtooth.sdk.protobuf.BatchOrBuilder getBatchOrBuilder();
}
