// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: genesis.proto

package sawtooth.sdk.protobuf;

public final class Genesis {
  private Genesis() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GenesisData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GenesisData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rgenesis.proto\032\013batch.proto\"&\n\013GenesisD" +
      "ata\022\027\n\007batches\030\001 \003(\0132\006.BatchB&\n\025sawtooth" +
      ".sdk.protobufP\001Z\013genesis_pb2b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          sawtooth.sdk.protobuf.BatchOuterClass.getDescriptor(),
        }, assigner);
    internal_static_GenesisData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GenesisData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GenesisData_descriptor,
        new java.lang.String[] { "Batches", });
    sawtooth.sdk.protobuf.BatchOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
