// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: network.proto

package sawtooth.sdk.protobuf;

/**
 * Protobuf type {@code GetPeersResponse}
 */
public  final class GetPeersResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GetPeersResponse)
    GetPeersResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetPeersResponse.newBuilder() to construct.
  private GetPeersResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetPeersResponse() {
    peerEndpoints_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetPeersResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              peerEndpoints_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            peerEndpoints_.add(s);
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        peerEndpoints_ = peerEndpoints_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return sawtooth.sdk.protobuf.Network.internal_static_GetPeersResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return sawtooth.sdk.protobuf.Network.internal_static_GetPeersResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            sawtooth.sdk.protobuf.GetPeersResponse.class, sawtooth.sdk.protobuf.GetPeersResponse.Builder.class);
  }

  public static final int PEER_ENDPOINTS_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList peerEndpoints_;
  /**
   * <code>repeated string peer_endpoints = 1;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getPeerEndpointsList() {
    return peerEndpoints_;
  }
  /**
   * <code>repeated string peer_endpoints = 1;</code>
   */
  public int getPeerEndpointsCount() {
    return peerEndpoints_.size();
  }
  /**
   * <code>repeated string peer_endpoints = 1;</code>
   */
  public java.lang.String getPeerEndpoints(int index) {
    return peerEndpoints_.get(index);
  }
  /**
   * <code>repeated string peer_endpoints = 1;</code>
   */
  public com.google.protobuf.ByteString
      getPeerEndpointsBytes(int index) {
    return peerEndpoints_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < peerEndpoints_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, peerEndpoints_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < peerEndpoints_.size(); i++) {
        dataSize += computeStringSizeNoTag(peerEndpoints_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getPeerEndpointsList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof sawtooth.sdk.protobuf.GetPeersResponse)) {
      return super.equals(obj);
    }
    sawtooth.sdk.protobuf.GetPeersResponse other = (sawtooth.sdk.protobuf.GetPeersResponse) obj;

    boolean result = true;
    result = result && getPeerEndpointsList()
        .equals(other.getPeerEndpointsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPeerEndpointsCount() > 0) {
      hash = (37 * hash) + PEER_ENDPOINTS_FIELD_NUMBER;
      hash = (53 * hash) + getPeerEndpointsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static sawtooth.sdk.protobuf.GetPeersResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sawtooth.sdk.protobuf.GetPeersResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sawtooth.sdk.protobuf.GetPeersResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sawtooth.sdk.protobuf.GetPeersResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sawtooth.sdk.protobuf.GetPeersResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sawtooth.sdk.protobuf.GetPeersResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sawtooth.sdk.protobuf.GetPeersResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sawtooth.sdk.protobuf.GetPeersResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static sawtooth.sdk.protobuf.GetPeersResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static sawtooth.sdk.protobuf.GetPeersResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static sawtooth.sdk.protobuf.GetPeersResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sawtooth.sdk.protobuf.GetPeersResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sawtooth.sdk.protobuf.GetPeersResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetPeersResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetPeersResponse)
      sawtooth.sdk.protobuf.GetPeersResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sawtooth.sdk.protobuf.Network.internal_static_GetPeersResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sawtooth.sdk.protobuf.Network.internal_static_GetPeersResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sawtooth.sdk.protobuf.GetPeersResponse.class, sawtooth.sdk.protobuf.GetPeersResponse.Builder.class);
    }

    // Construct using sawtooth.sdk.protobuf.GetPeersResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      peerEndpoints_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return sawtooth.sdk.protobuf.Network.internal_static_GetPeersResponse_descriptor;
    }

    @java.lang.Override
    public sawtooth.sdk.protobuf.GetPeersResponse getDefaultInstanceForType() {
      return sawtooth.sdk.protobuf.GetPeersResponse.getDefaultInstance();
    }

    @java.lang.Override
    public sawtooth.sdk.protobuf.GetPeersResponse build() {
      sawtooth.sdk.protobuf.GetPeersResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public sawtooth.sdk.protobuf.GetPeersResponse buildPartial() {
      sawtooth.sdk.protobuf.GetPeersResponse result = new sawtooth.sdk.protobuf.GetPeersResponse(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        peerEndpoints_ = peerEndpoints_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.peerEndpoints_ = peerEndpoints_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof sawtooth.sdk.protobuf.GetPeersResponse) {
        return mergeFrom((sawtooth.sdk.protobuf.GetPeersResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(sawtooth.sdk.protobuf.GetPeersResponse other) {
      if (other == sawtooth.sdk.protobuf.GetPeersResponse.getDefaultInstance()) return this;
      if (!other.peerEndpoints_.isEmpty()) {
        if (peerEndpoints_.isEmpty()) {
          peerEndpoints_ = other.peerEndpoints_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensurePeerEndpointsIsMutable();
          peerEndpoints_.addAll(other.peerEndpoints_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      sawtooth.sdk.protobuf.GetPeersResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (sawtooth.sdk.protobuf.GetPeersResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList peerEndpoints_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensurePeerEndpointsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        peerEndpoints_ = new com.google.protobuf.LazyStringArrayList(peerEndpoints_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string peer_endpoints = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getPeerEndpointsList() {
      return peerEndpoints_.getUnmodifiableView();
    }
    /**
     * <code>repeated string peer_endpoints = 1;</code>
     */
    public int getPeerEndpointsCount() {
      return peerEndpoints_.size();
    }
    /**
     * <code>repeated string peer_endpoints = 1;</code>
     */
    public java.lang.String getPeerEndpoints(int index) {
      return peerEndpoints_.get(index);
    }
    /**
     * <code>repeated string peer_endpoints = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPeerEndpointsBytes(int index) {
      return peerEndpoints_.getByteString(index);
    }
    /**
     * <code>repeated string peer_endpoints = 1;</code>
     */
    public Builder setPeerEndpoints(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensurePeerEndpointsIsMutable();
      peerEndpoints_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string peer_endpoints = 1;</code>
     */
    public Builder addPeerEndpoints(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensurePeerEndpointsIsMutable();
      peerEndpoints_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string peer_endpoints = 1;</code>
     */
    public Builder addAllPeerEndpoints(
        java.lang.Iterable<java.lang.String> values) {
      ensurePeerEndpointsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, peerEndpoints_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string peer_endpoints = 1;</code>
     */
    public Builder clearPeerEndpoints() {
      peerEndpoints_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string peer_endpoints = 1;</code>
     */
    public Builder addPeerEndpointsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensurePeerEndpointsIsMutable();
      peerEndpoints_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GetPeersResponse)
  }

  // @@protoc_insertion_point(class_scope:GetPeersResponse)
  private static final sawtooth.sdk.protobuf.GetPeersResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new sawtooth.sdk.protobuf.GetPeersResponse();
  }

  public static sawtooth.sdk.protobuf.GetPeersResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetPeersResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetPeersResponse>() {
    @java.lang.Override
    public GetPeersResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetPeersResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetPeersResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetPeersResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public sawtooth.sdk.protobuf.GetPeersResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

