// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: network.proto

package sawtooth.sdk.protobuf;

public interface GossipBatchByBatchIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GossipBatchByBatchIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The id of the batch that is being requested
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <pre>
   * The id of the batch that is being requested
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * A random string that provides uniqueness for requests with
   * otherwise identical fields.
   * </pre>
   *
   * <code>string nonce = 2;</code>
   */
  java.lang.String getNonce();
  /**
   * <pre>
   * A random string that provides uniqueness for requests with
   * otherwise identical fields.
   * </pre>
   *
   * <code>string nonce = 2;</code>
   */
  com.google.protobuf.ByteString
      getNonceBytes();

  /**
   * <code>uint32 time_to_live = 3;</code>
   */
  int getTimeToLive();
}
