// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: merkle.proto

package sawtooth.sdk.protobuf;

public final class Merkle {
  private Merkle() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChangeLogEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChangeLogEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChangeLogEntry_Successor_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChangeLogEntry_Successor_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014merkle.proto\"\225\001\n\016ChangeLogEntry\022\016\n\006par" +
      "ent\030\001 \001(\014\022\021\n\tadditions\030\002 \003(\014\022-\n\nsuccesso" +
      "rs\030\003 \003(\0132\031.ChangeLogEntry.Successor\0321\n\tS" +
      "uccessor\022\021\n\tsuccessor\030\001 \001(\014\022\021\n\tdeletions" +
      "\030\002 \003(\014B%\n\025sawtooth.sdk.protobufP\001Z\nmerkl" +
      "e_pb2b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ChangeLogEntry_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ChangeLogEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChangeLogEntry_descriptor,
        new java.lang.String[] { "Parent", "Additions", "Successors", });
    internal_static_ChangeLogEntry_Successor_descriptor =
      internal_static_ChangeLogEntry_descriptor.getNestedTypes().get(0);
    internal_static_ChangeLogEntry_Successor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChangeLogEntry_Successor_descriptor,
        new java.lang.String[] { "Successor", "Deletions", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
