// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: validator.proto

package sawtooth.sdk.protobuf;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The type of message, used to determine how to 'route' the message
   * to the appropriate handler as well as how to deserialize the
   * content.
   * </pre>
   *
   * <code>.Message.MessageType message_type = 1;</code>
   */
  int getMessageTypeValue();
  /**
   * <pre>
   * The type of message, used to determine how to 'route' the message
   * to the appropriate handler as well as how to deserialize the
   * content.
   * </pre>
   *
   * <code>.Message.MessageType message_type = 1;</code>
   */
  sawtooth.sdk.protobuf.Message.MessageType getMessageType();

  /**
   * <pre>
   * The identifier used to correlate response messages to their related
   * request messages.  correlation_id should be set to a random string
   * for messages which are not responses to previously sent messages.  For
   * response messages, correlation_id should be set to the same string as
   * contained in the request message.
   * </pre>
   *
   * <code>string correlation_id = 2;</code>
   */
  java.lang.String getCorrelationId();
  /**
   * <pre>
   * The identifier used to correlate response messages to their related
   * request messages.  correlation_id should be set to a random string
   * for messages which are not responses to previously sent messages.  For
   * response messages, correlation_id should be set to the same string as
   * contained in the request message.
   * </pre>
   *
   * <code>string correlation_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getCorrelationIdBytes();

  /**
   * <pre>
   * The content of the message, defined by message_type.  In many
   * cases, this data has been serialized with Protocol Buffers or
   * CBOR.
   * </pre>
   *
   * <code>bytes content = 3;</code>
   */
  com.google.protobuf.ByteString getContent();
}
