// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: network.proto

package sawtooth.sdk.protobuf;

public final class Network {
  private Network() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DisconnectMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DisconnectMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PeerRegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PeerRegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PeerUnregisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PeerUnregisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetPeersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetPeersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetPeersResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetPeersResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GossipMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GossipMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NetworkAcknowledgement_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NetworkAcknowledgement_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GossipBlockRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GossipBlockRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GossipBlockResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GossipBlockResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GossipBatchResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GossipBatchResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GossipBatchByBatchIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GossipBatchByBatchIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GossipBatchByTransactionIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GossipBatchByTransactionIdRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rnetwork.proto\"\023\n\021DisconnectMessage\"A\n\023" +
      "PeerRegisterRequest\022\020\n\010endpoint\030\001 \001(\t\022\030\n" +
      "\020protocol_version\030\002 \001(\r\"\027\n\025PeerUnregiste" +
      "rRequest\"\021\n\017GetPeersRequest\"*\n\020GetPeersR" +
      "esponse\022\026\n\016peer_endpoints\030\001 \003(\t\"\r\n\013PingR" +
      "equest\"\016\n\014PingResponse\"\245\001\n\rGossipMessage" +
      "\022\017\n\007content\030\001 \001(\014\0220\n\014content_type\030\002 \001(\0162" +
      "\032.GossipMessage.ContentType\022\024\n\014time_to_l" +
      "ive\030\003 \001(\r\";\n\013ContentType\022\026\n\022CONTENT_TYPE" +
      "_UNSET\020\000\022\t\n\005BLOCK\020\001\022\t\n\005BATCH\020\002\"w\n\026Networ" +
      "kAcknowledgement\022.\n\006status\030\001 \001(\0162\036.Netwo" +
      "rkAcknowledgement.Status\"-\n\006Status\022\020\n\014ST" +
      "ATUS_UNSET\020\000\022\006\n\002OK\020\001\022\t\n\005ERROR\020\002\"K\n\022Gossi" +
      "pBlockRequest\022\020\n\010block_id\030\001 \001(\t\022\r\n\005nonce" +
      "\030\002 \001(\t\022\024\n\014time_to_live\030\003 \001(\r\"&\n\023GossipBl" +
      "ockResponse\022\017\n\007content\030\001 \001(\014\"&\n\023GossipBa" +
      "tchResponse\022\017\n\007content\030\001 \001(\014\"N\n\033GossipBa" +
      "tchByBatchIdRequest\022\n\n\002id\030\001 \001(\t\022\r\n\005nonce" +
      "\030\002 \001(\t\022\024\n\014time_to_live\030\003 \001(\r\"U\n!GossipBa" +
      "tchByTransactionIdRequest\022\013\n\003ids\030\001 \003(\t\022\r" +
      "\n\005nonce\030\002 \001(\t\022\024\n\014time_to_live\030\003 \001(\rB&\n\025s" +
      "awtooth.sdk.protobufP\001Z\013network_pb2b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_DisconnectMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DisconnectMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DisconnectMessage_descriptor,
        new java.lang.String[] { });
    internal_static_PeerRegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PeerRegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PeerRegisterRequest_descriptor,
        new java.lang.String[] { "Endpoint", "ProtocolVersion", });
    internal_static_PeerUnregisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PeerUnregisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PeerUnregisterRequest_descriptor,
        new java.lang.String[] { });
    internal_static_GetPeersRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_GetPeersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetPeersRequest_descriptor,
        new java.lang.String[] { });
    internal_static_GetPeersResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_GetPeersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetPeersResponse_descriptor,
        new java.lang.String[] { "PeerEndpoints", });
    internal_static_PingRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_PingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PingRequest_descriptor,
        new java.lang.String[] { });
    internal_static_PingResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_PingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PingResponse_descriptor,
        new java.lang.String[] { });
    internal_static_GossipMessage_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_GossipMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GossipMessage_descriptor,
        new java.lang.String[] { "Content", "ContentType", "TimeToLive", });
    internal_static_NetworkAcknowledgement_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_NetworkAcknowledgement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NetworkAcknowledgement_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_GossipBlockRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_GossipBlockRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GossipBlockRequest_descriptor,
        new java.lang.String[] { "BlockId", "Nonce", "TimeToLive", });
    internal_static_GossipBlockResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_GossipBlockResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GossipBlockResponse_descriptor,
        new java.lang.String[] { "Content", });
    internal_static_GossipBatchResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_GossipBatchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GossipBatchResponse_descriptor,
        new java.lang.String[] { "Content", });
    internal_static_GossipBatchByBatchIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_GossipBatchByBatchIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GossipBatchByBatchIdRequest_descriptor,
        new java.lang.String[] { "Id", "Nonce", "TimeToLive", });
    internal_static_GossipBatchByTransactionIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_GossipBatchByTransactionIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GossipBatchByTransactionIdRequest_descriptor,
        new java.lang.String[] { "Ids", "Nonce", "TimeToLive", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
