// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: network.proto

package sawtooth.sdk.protobuf;

public interface PeerUnregisterRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PeerUnregisterRequest)
    com.google.protobuf.MessageOrBuilder {
}
