// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: network.proto

package sawtooth.sdk.protobuf;

public interface PingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PingRequest)
    com.google.protobuf.MessageOrBuilder {
}
