// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transaction_receipt.proto

package sawtooth.sdk.protobuf;

public interface StateChangeListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StateChangeList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .StateChange state_changes = 1;</code>
   */
  java.util.List<sawtooth.sdk.protobuf.StateChange> 
      getStateChangesList();
  /**
   * <code>repeated .StateChange state_changes = 1;</code>
   */
  sawtooth.sdk.protobuf.StateChange getStateChanges(int index);
  /**
   * <code>repeated .StateChange state_changes = 1;</code>
   */
  int getStateChangesCount();
  /**
   * <code>repeated .StateChange state_changes = 1;</code>
   */
  java.util.List<? extends sawtooth.sdk.protobuf.StateChangeOrBuilder> 
      getStateChangesOrBuilderList();
  /**
   * <code>repeated .StateChange state_changes = 1;</code>
   */
  sawtooth.sdk.protobuf.StateChangeOrBuilder getStateChangesOrBuilder(
      int index);
}
