// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: processor.proto

package sawtooth.sdk.protobuf;

/**
 * <pre>
 * The registration request from the transaction processor to the
 * validator/executor
 * </pre>
 *
 * Protobuf type {@code TpRegisterRequest}
 */
public  final class TpRegisterRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TpRegisterRequest)
    TpRegisterRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TpRegisterRequest.newBuilder() to construct.
  private TpRegisterRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TpRegisterRequest() {
    family_ = "";
    version_ = "";
    namespaces_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    maxOccupancy_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TpRegisterRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            family_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            version_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              namespaces_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000004;
            }
            namespaces_.add(s);
            break;
          }
          case 40: {

            maxOccupancy_ = input.readUInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        namespaces_ = namespaces_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return sawtooth.sdk.protobuf.Processor.internal_static_TpRegisterRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return sawtooth.sdk.protobuf.Processor.internal_static_TpRegisterRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            sawtooth.sdk.protobuf.TpRegisterRequest.class, sawtooth.sdk.protobuf.TpRegisterRequest.Builder.class);
  }

  private int bitField0_;
  public static final int FAMILY_FIELD_NUMBER = 1;
  private volatile java.lang.Object family_;
  /**
   * <pre>
   * A settled upon name for the capabilities of the transaction processor.
   * For example: intkey, xo
   * </pre>
   *
   * <code>string family = 1;</code>
   */
  public java.lang.String getFamily() {
    java.lang.Object ref = family_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      family_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * A settled upon name for the capabilities of the transaction processor.
   * For example: intkey, xo
   * </pre>
   *
   * <code>string family = 1;</code>
   */
  public com.google.protobuf.ByteString
      getFamilyBytes() {
    java.lang.Object ref = family_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      family_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERSION_FIELD_NUMBER = 2;
  private volatile java.lang.Object version_;
  /**
   * <pre>
   * The version supported.  For example:
   *      1.0  for version 1.0
   *      2.1  for version 2.1
   * </pre>
   *
   * <code>string version = 2;</code>
   */
  public java.lang.String getVersion() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      version_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The version supported.  For example:
   *      1.0  for version 1.0
   *      2.1  for version 2.1
   * </pre>
   *
   * <code>string version = 2;</code>
   */
  public com.google.protobuf.ByteString
      getVersionBytes() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      version_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAMESPACES_FIELD_NUMBER = 4;
  private com.google.protobuf.LazyStringList namespaces_;
  /**
   * <pre>
   * The namespaces this transaction processor expects to interact with
   * when processing transactions matching this specification; will be
   * enforced by the state API on the validator.
   * </pre>
   *
   * <code>repeated string namespaces = 4;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getNamespacesList() {
    return namespaces_;
  }
  /**
   * <pre>
   * The namespaces this transaction processor expects to interact with
   * when processing transactions matching this specification; will be
   * enforced by the state API on the validator.
   * </pre>
   *
   * <code>repeated string namespaces = 4;</code>
   */
  public int getNamespacesCount() {
    return namespaces_.size();
  }
  /**
   * <pre>
   * The namespaces this transaction processor expects to interact with
   * when processing transactions matching this specification; will be
   * enforced by the state API on the validator.
   * </pre>
   *
   * <code>repeated string namespaces = 4;</code>
   */
  public java.lang.String getNamespaces(int index) {
    return namespaces_.get(index);
  }
  /**
   * <pre>
   * The namespaces this transaction processor expects to interact with
   * when processing transactions matching this specification; will be
   * enforced by the state API on the validator.
   * </pre>
   *
   * <code>repeated string namespaces = 4;</code>
   */
  public com.google.protobuf.ByteString
      getNamespacesBytes(int index) {
    return namespaces_.getByteString(index);
  }

  public static final int MAX_OCCUPANCY_FIELD_NUMBER = 5;
  private int maxOccupancy_;
  /**
   * <pre>
   * The maximum number of transactions that this transaction processor can
   * handle at once.
   * </pre>
   *
   * <code>uint32 max_occupancy = 5;</code>
   */
  public int getMaxOccupancy() {
    return maxOccupancy_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getFamilyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, family_);
    }
    if (!getVersionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, version_);
    }
    for (int i = 0; i < namespaces_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, namespaces_.getRaw(i));
    }
    if (maxOccupancy_ != 0) {
      output.writeUInt32(5, maxOccupancy_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getFamilyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, family_);
    }
    if (!getVersionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, version_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < namespaces_.size(); i++) {
        dataSize += computeStringSizeNoTag(namespaces_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getNamespacesList().size();
    }
    if (maxOccupancy_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, maxOccupancy_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof sawtooth.sdk.protobuf.TpRegisterRequest)) {
      return super.equals(obj);
    }
    sawtooth.sdk.protobuf.TpRegisterRequest other = (sawtooth.sdk.protobuf.TpRegisterRequest) obj;

    boolean result = true;
    result = result && getFamily()
        .equals(other.getFamily());
    result = result && getVersion()
        .equals(other.getVersion());
    result = result && getNamespacesList()
        .equals(other.getNamespacesList());
    result = result && (getMaxOccupancy()
        == other.getMaxOccupancy());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FAMILY_FIELD_NUMBER;
    hash = (53 * hash) + getFamily().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion().hashCode();
    if (getNamespacesCount() > 0) {
      hash = (37 * hash) + NAMESPACES_FIELD_NUMBER;
      hash = (53 * hash) + getNamespacesList().hashCode();
    }
    hash = (37 * hash) + MAX_OCCUPANCY_FIELD_NUMBER;
    hash = (53 * hash) + getMaxOccupancy();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static sawtooth.sdk.protobuf.TpRegisterRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sawtooth.sdk.protobuf.TpRegisterRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sawtooth.sdk.protobuf.TpRegisterRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sawtooth.sdk.protobuf.TpRegisterRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sawtooth.sdk.protobuf.TpRegisterRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sawtooth.sdk.protobuf.TpRegisterRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sawtooth.sdk.protobuf.TpRegisterRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sawtooth.sdk.protobuf.TpRegisterRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static sawtooth.sdk.protobuf.TpRegisterRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static sawtooth.sdk.protobuf.TpRegisterRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static sawtooth.sdk.protobuf.TpRegisterRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sawtooth.sdk.protobuf.TpRegisterRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sawtooth.sdk.protobuf.TpRegisterRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The registration request from the transaction processor to the
   * validator/executor
   * </pre>
   *
   * Protobuf type {@code TpRegisterRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TpRegisterRequest)
      sawtooth.sdk.protobuf.TpRegisterRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sawtooth.sdk.protobuf.Processor.internal_static_TpRegisterRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sawtooth.sdk.protobuf.Processor.internal_static_TpRegisterRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sawtooth.sdk.protobuf.TpRegisterRequest.class, sawtooth.sdk.protobuf.TpRegisterRequest.Builder.class);
    }

    // Construct using sawtooth.sdk.protobuf.TpRegisterRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      family_ = "";

      version_ = "";

      namespaces_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      maxOccupancy_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return sawtooth.sdk.protobuf.Processor.internal_static_TpRegisterRequest_descriptor;
    }

    @java.lang.Override
    public sawtooth.sdk.protobuf.TpRegisterRequest getDefaultInstanceForType() {
      return sawtooth.sdk.protobuf.TpRegisterRequest.getDefaultInstance();
    }

    @java.lang.Override
    public sawtooth.sdk.protobuf.TpRegisterRequest build() {
      sawtooth.sdk.protobuf.TpRegisterRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public sawtooth.sdk.protobuf.TpRegisterRequest buildPartial() {
      sawtooth.sdk.protobuf.TpRegisterRequest result = new sawtooth.sdk.protobuf.TpRegisterRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.family_ = family_;
      result.version_ = version_;
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        namespaces_ = namespaces_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.namespaces_ = namespaces_;
      result.maxOccupancy_ = maxOccupancy_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof sawtooth.sdk.protobuf.TpRegisterRequest) {
        return mergeFrom((sawtooth.sdk.protobuf.TpRegisterRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(sawtooth.sdk.protobuf.TpRegisterRequest other) {
      if (other == sawtooth.sdk.protobuf.TpRegisterRequest.getDefaultInstance()) return this;
      if (!other.getFamily().isEmpty()) {
        family_ = other.family_;
        onChanged();
      }
      if (!other.getVersion().isEmpty()) {
        version_ = other.version_;
        onChanged();
      }
      if (!other.namespaces_.isEmpty()) {
        if (namespaces_.isEmpty()) {
          namespaces_ = other.namespaces_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureNamespacesIsMutable();
          namespaces_.addAll(other.namespaces_);
        }
        onChanged();
      }
      if (other.getMaxOccupancy() != 0) {
        setMaxOccupancy(other.getMaxOccupancy());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      sawtooth.sdk.protobuf.TpRegisterRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (sawtooth.sdk.protobuf.TpRegisterRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object family_ = "";
    /**
     * <pre>
     * A settled upon name for the capabilities of the transaction processor.
     * For example: intkey, xo
     * </pre>
     *
     * <code>string family = 1;</code>
     */
    public java.lang.String getFamily() {
      java.lang.Object ref = family_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        family_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * A settled upon name for the capabilities of the transaction processor.
     * For example: intkey, xo
     * </pre>
     *
     * <code>string family = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFamilyBytes() {
      java.lang.Object ref = family_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        family_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * A settled upon name for the capabilities of the transaction processor.
     * For example: intkey, xo
     * </pre>
     *
     * <code>string family = 1;</code>
     */
    public Builder setFamily(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      family_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A settled upon name for the capabilities of the transaction processor.
     * For example: intkey, xo
     * </pre>
     *
     * <code>string family = 1;</code>
     */
    public Builder clearFamily() {
      
      family_ = getDefaultInstance().getFamily();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A settled upon name for the capabilities of the transaction processor.
     * For example: intkey, xo
     * </pre>
     *
     * <code>string family = 1;</code>
     */
    public Builder setFamilyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      family_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object version_ = "";
    /**
     * <pre>
     * The version supported.  For example:
     *      1.0  for version 1.0
     *      2.1  for version 2.1
     * </pre>
     *
     * <code>string version = 2;</code>
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The version supported.  For example:
     *      1.0  for version 1.0
     *      2.1  for version 2.1
     * </pre>
     *
     * <code>string version = 2;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The version supported.  For example:
     *      1.0  for version 1.0
     *      2.1  for version 2.1
     * </pre>
     *
     * <code>string version = 2;</code>
     */
    public Builder setVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The version supported.  For example:
     *      1.0  for version 1.0
     *      2.1  for version 2.1
     * </pre>
     *
     * <code>string version = 2;</code>
     */
    public Builder clearVersion() {
      
      version_ = getDefaultInstance().getVersion();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The version supported.  For example:
     *      1.0  for version 1.0
     *      2.1  for version 2.1
     * </pre>
     *
     * <code>string version = 2;</code>
     */
    public Builder setVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      version_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList namespaces_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureNamespacesIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        namespaces_ = new com.google.protobuf.LazyStringArrayList(namespaces_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <pre>
     * The namespaces this transaction processor expects to interact with
     * when processing transactions matching this specification; will be
     * enforced by the state API on the validator.
     * </pre>
     *
     * <code>repeated string namespaces = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getNamespacesList() {
      return namespaces_.getUnmodifiableView();
    }
    /**
     * <pre>
     * The namespaces this transaction processor expects to interact with
     * when processing transactions matching this specification; will be
     * enforced by the state API on the validator.
     * </pre>
     *
     * <code>repeated string namespaces = 4;</code>
     */
    public int getNamespacesCount() {
      return namespaces_.size();
    }
    /**
     * <pre>
     * The namespaces this transaction processor expects to interact with
     * when processing transactions matching this specification; will be
     * enforced by the state API on the validator.
     * </pre>
     *
     * <code>repeated string namespaces = 4;</code>
     */
    public java.lang.String getNamespaces(int index) {
      return namespaces_.get(index);
    }
    /**
     * <pre>
     * The namespaces this transaction processor expects to interact with
     * when processing transactions matching this specification; will be
     * enforced by the state API on the validator.
     * </pre>
     *
     * <code>repeated string namespaces = 4;</code>
     */
    public com.google.protobuf.ByteString
        getNamespacesBytes(int index) {
      return namespaces_.getByteString(index);
    }
    /**
     * <pre>
     * The namespaces this transaction processor expects to interact with
     * when processing transactions matching this specification; will be
     * enforced by the state API on the validator.
     * </pre>
     *
     * <code>repeated string namespaces = 4;</code>
     */
    public Builder setNamespaces(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureNamespacesIsMutable();
      namespaces_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The namespaces this transaction processor expects to interact with
     * when processing transactions matching this specification; will be
     * enforced by the state API on the validator.
     * </pre>
     *
     * <code>repeated string namespaces = 4;</code>
     */
    public Builder addNamespaces(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureNamespacesIsMutable();
      namespaces_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The namespaces this transaction processor expects to interact with
     * when processing transactions matching this specification; will be
     * enforced by the state API on the validator.
     * </pre>
     *
     * <code>repeated string namespaces = 4;</code>
     */
    public Builder addAllNamespaces(
        java.lang.Iterable<java.lang.String> values) {
      ensureNamespacesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, namespaces_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The namespaces this transaction processor expects to interact with
     * when processing transactions matching this specification; will be
     * enforced by the state API on the validator.
     * </pre>
     *
     * <code>repeated string namespaces = 4;</code>
     */
    public Builder clearNamespaces() {
      namespaces_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The namespaces this transaction processor expects to interact with
     * when processing transactions matching this specification; will be
     * enforced by the state API on the validator.
     * </pre>
     *
     * <code>repeated string namespaces = 4;</code>
     */
    public Builder addNamespacesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureNamespacesIsMutable();
      namespaces_.add(value);
      onChanged();
      return this;
    }

    private int maxOccupancy_ ;
    /**
     * <pre>
     * The maximum number of transactions that this transaction processor can
     * handle at once.
     * </pre>
     *
     * <code>uint32 max_occupancy = 5;</code>
     */
    public int getMaxOccupancy() {
      return maxOccupancy_;
    }
    /**
     * <pre>
     * The maximum number of transactions that this transaction processor can
     * handle at once.
     * </pre>
     *
     * <code>uint32 max_occupancy = 5;</code>
     */
    public Builder setMaxOccupancy(int value) {
      
      maxOccupancy_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The maximum number of transactions that this transaction processor can
     * handle at once.
     * </pre>
     *
     * <code>uint32 max_occupancy = 5;</code>
     */
    public Builder clearMaxOccupancy() {
      
      maxOccupancy_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:TpRegisterRequest)
  }

  // @@protoc_insertion_point(class_scope:TpRegisterRequest)
  private static final sawtooth.sdk.protobuf.TpRegisterRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new sawtooth.sdk.protobuf.TpRegisterRequest();
  }

  public static sawtooth.sdk.protobuf.TpRegisterRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TpRegisterRequest>
      PARSER = new com.google.protobuf.AbstractParser<TpRegisterRequest>() {
    @java.lang.Override
    public TpRegisterRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TpRegisterRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TpRegisterRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TpRegisterRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public sawtooth.sdk.protobuf.TpRegisterRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

