// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: processor.proto

package sawtooth.sdk.protobuf;

public interface TpUnregisterResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TpUnregisterResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.TpUnregisterResponse.Status status = 1;</code>
   */
  int getStatusValue();
  /**
   * <code>.TpUnregisterResponse.Status status = 1;</code>
   */
  sawtooth.sdk.protobuf.TpUnregisterResponse.Status getStatus();
}
