// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transaction_receipt.proto

package sawtooth.sdk.protobuf;

public final class TransactionReceiptOuterClass {
  private TransactionReceiptOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransactionReceipt_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TransactionReceipt_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StateChange_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StateChange_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StateChangeList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StateChangeList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031transaction_receipt.proto\032\014events.prot" +
      "o\"w\n\022TransactionReceipt\022#\n\rstate_changes" +
      "\030\001 \003(\0132\014.StateChange\022\026\n\006events\030\002 \003(\0132\006.E" +
      "vent\022\014\n\004data\030\003 \003(\014\022\026\n\016transaction_id\030\004 \001" +
      "(\t\"{\n\013StateChange\022\017\n\007address\030\001 \001(\t\022\r\n\005va" +
      "lue\030\002 \001(\014\022\037\n\004type\030\003 \001(\0162\021.StateChange.Ty" +
      "pe\"+\n\004Type\022\016\n\nTYPE_UNSET\020\000\022\007\n\003SET\020\001\022\n\n\006D" +
      "ELETE\020\002\"6\n\017StateChangeList\022#\n\rstate_chan" +
      "ges\030\001 \003(\0132\014.StateChangeB*\n\025sawtooth.sdk." +
      "protobufP\001Z\017txn_receipt_pb2b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          sawtooth.sdk.protobuf.Events.getDescriptor(),
        }, assigner);
    internal_static_TransactionReceipt_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TransactionReceipt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TransactionReceipt_descriptor,
        new java.lang.String[] { "StateChanges", "Events", "Data", "TransactionId", });
    internal_static_StateChange_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_StateChange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StateChange_descriptor,
        new java.lang.String[] { "Address", "Value", "Type", });
    internal_static_StateChangeList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_StateChangeList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StateChangeList_descriptor,
        new java.lang.String[] { "StateChanges", });
    sawtooth.sdk.protobuf.Events.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
